<?php

namespace Database\Seeders\Default;

use App\Models\Role;
use App\Models\User;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    const TEACHERS = [
        [
            "firstName" => "Евгений Владимирович",
            "lastName" => "Лебедев",
            "shortName" => "Лебедев Е.В.",
            "gender" => "мужской",
            "username" => "lebedevev",
        ],
        [
            "firstName" => "Мария Андреевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева М.А.",
            "gender" => "женский",
            "username" => "kovalevama",
        ],
        [
            "firstName" => "Мария Андреевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева М.А.",
            "gender" => "женский",
            "username" => "kovalevama2",
        ],
        [
            "firstName" => "Мария Андреевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева М.А.",
            "gender" => "женский",
            "username" => "kovalevama3",
        ],
        [
            "firstName" => "Андрей Игоревич",
            "lastName" => "Попов",
            "shortName" => "Попов А.И.",
            "gender" => "мужской",
            "username" => "popovai",
        ],
        [
            "firstName" => "Оксана Сергеевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.С.",
            "gender" => "женский",
            "username" => "petrovaos",
        ],
        [
            "firstName" => "Иван Васильевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров И.В.",
            "gender" => "мужской",
            "username" => "fedoroviv",
        ],
        [
            "firstName" => "Анастасия Владимировна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.В.",
            "gender" => "женский",
            "username" => "smirnovaav",
        ],
        [
            "firstName" => "Александр Анатольевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.А.",
            "gender" => "мужской",
            "username" => "kuznetsovaa",
        ],
        [
            "firstName" => "Светлана Викторовна",
            "lastName" => "Новикова",
            "shortName" => "Новикова С.В.",
            "gender" => "женский",
            "username" => "novikovasv",
        ],
        [
            "firstName" => "Игорь Александрович",
            "lastName" => "Иванов",
            "shortName" => "Иванов И.А.",
            "gender" => "мужской",
            "username" => "ivanovia",
        ],
        [
            "firstName" => "Наталья Ивановна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Н.И.",
            "gender" => "женский",
            "username" => "kozlovani",
        ],
        [
            "firstName" => "Дмитрий Васильевич",
            "lastName" => "Попов",
            "shortName" => "Попов Д.В.",
            "gender" => "мужской",
            "username" => "popovdv",
        ],
        [
            "firstName" => "Анастасия Ивановна",
            "lastName" => "Соколова",
            "shortName" => "Соколова А.И.",
            "gender" => "женский",
            "username" => "sokolovaai",
        ],
        [
            "firstName" => "Виктор Владимирович",
            "lastName" => "Новиков",
            "shortName" => "Новиков В.В.",
            "gender" => "мужской",
            "username" => "novikovvv",
        ],
        [
            "firstName" => "Анна Сергеевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.С.",
            "gender" => "женский",
            "username" => "ivanovaas",
        ],
        [
            "firstName" => "Алексей Васильевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.В.",
            "gender" => "мужской",
            "username" => "fedorovav",
        ],
        [
            "firstName" => "Елена Васильевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.В.",
            "gender" => "женский",
            "username" => "petrovaev",
        ],
        [
            "firstName" => "Владимир Андреевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов В.А.",
            "gender" => "мужской",
            "username" => "kuznetsovva",
        ],
        [
            "firstName" => "Нина Владимировна",
            "lastName" => "Попова",
            "shortName" => "Попова Н.В.",
            "gender" => "женский",
            "username" => "popovanv",
        ],
        [
            "firstName" => "Иван Петрович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.П.",
            "gender" => "мужской",
            "username" => "smirnovip",
        ],
        [
            "firstName" => "Анна Александровна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.А.",
            "gender" => "женский",
            "username" => "kovalevaaa",
        ],
        [
            "firstName" => "Ольга Сергеевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова О.С.",
            "gender" => "женский",
            "username" => "kuznetsovaos",
        ],
        [
            "firstName" => "Алексей Иванович",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.И.",
            "gender" => "мужской",
            "username" => "ivanovai",
        ],
        [
            "firstName" => "Екатерина Владимировна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.В.",
            "gender" => "женский",
            "username" => "novikovaev",
        ],
        [
            "firstName" => "Александр Александрович",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.А.",
            "gender" => "мужской",
            "username" => "kozlovaa",
        ],
        [
            "firstName" => "Ирина Андреевна",
            "lastName" => "Попова",
            "shortName" => "Попова И.А.",
            "gender" => "женский",
            "username" => "popovaia",
        ],
        [
            "firstName" => "Владислав Иванович",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.И.",
            "gender" => "мужской",
            "username" => "sokolovvi",
        ],
        [
            "firstName" => "Татьяна Сергеевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Т.С.",
            "gender" => "женский",
            "username" => "fedorovats",
        ],
        [
            "firstName" => "Артем Александрович",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.А.",
            "gender" => "мужской",
            "username" => "ivanovaa",
        ],
        [
            "firstName" => "Юлия Викторовна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Ю.В.",
            "gender" => "женский",
            "username" => "kovalevaiuv",
        ],
        [
            "firstName" => "Сергей Иванович",
            "lastName" => "Петров",
            "shortName" => "Петров С.И.",
            "gender" => "мужской",
            "username" => "petrovsi",
        ],
        [
            "firstName" => "Нина Андреевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Н.А.",
            "gender" => "женский",
            "username" => "kuznetsovana",
        ],
        [
            "firstName" => "Андрей Александрович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов А.А.",
            "gender" => "мужской",
            "username" => "smirnovaa",
        ],
        [
            "firstName" => "Марина Васильевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова М.В.",
            "gender" => "женский",
            "username" => "novikovamv",
        ],
        [
            "firstName" => "Игорь Владимирович",
            "lastName" => "Козлов",
            "shortName" => "Козлов И.В.",
            "gender" => "мужской",
            "username" => "kozloviv",
        ],
        [
            "firstName" => "Елена Игоревна",
            "lastName" => "Попова",
            "shortName" => "Попова Е.И.",
            "gender" => "женский",
            "username" => "popovaei",
        ],
        [
            "firstName" => "Алексей Андреевич",
            "lastName" => "Соколов",
            "shortName" => "Соколов А.А.",
            "gender" => "мужской",
            "username" => "sokolovaa",
        ],
        [
            "firstName" => "Мария Ивановна",
            "lastName" => "Федорова",
            "shortName" => "Федорова М.И.",
            "gender" => "женский",
            "username" => "fedorovami",
        ],
        [
            "firstName" => "Владимир Васильевич",
            "lastName" => "Иванов",
            "shortName" => "Иванов В.В.",
            "gender" => "мужской",
            "username" => "ivanovvv",
        ],
        [
            "firstName" => "Ольга Викторовна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева О.В.",
            "gender" => "женский",
            "username" => "kovalevaov",
        ],
        [
            "firstName" => "Денис Владимирович",
            "lastName" => "Петров",
            "shortName" => "Петров Д.В.",
            "gender" => "мужской",
            "username" => "petrovdv",
        ],
        [
            "firstName" => "Иван Андреевич",
            "lastName" => "Иванов",
            "shortName" => "Иванов И.А.",
            "gender" => "мужской",
            "username" => "ivanovia2",
        ],
        [
            "firstName" => "Анна Владимировна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.В.",
            "gender" => "женский",
            "username" => "novikovaav",
        ],
        [
            "firstName" => "Владислав Васильевич",
            "lastName" => "Козлов",
            "shortName" => "Козлов В.В.",
            "gender" => "мужской",
            "username" => "kozlovvv",
        ],
        [
            "firstName" => "Алина Александровна",
            "lastName" => "Попова",
            "shortName" => "Попова А.А.",
            "gender" => "женский",
            "username" => "popovaaa",
        ],
        [
            "firstName" => "Алексей Викторович",
            "lastName" => "Соколов",
            "shortName" => "Соколов А.В.",
            "gender" => "мужской",
            "username" => "sokolovav",
        ],
        [
            "firstName" => "Ирина Васильевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.В.",
            "gender" => "женский",
            "username" => "fedorovaiv",
        ],
        [
            "firstName" => "Михаил Игоревич",
            "lastName" => "Иванов",
            "shortName" => "Иванов М.И.",
            "gender" => "мужской",
            "username" => "ivanovmi",
        ],
        [
            "firstName" => "Ангелина Александровна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.А.",
            "gender" => "женский",
            "username" => "kovalevaaa2",
        ],
        [
            "firstName" => "Петр Сергеевич",
            "lastName" => "Петров",
            "shortName" => "Петров П.С.",
            "gender" => "мужской",
            "username" => "petrovps",
        ],
        [
            "firstName" => "Валерия Владимировна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова В.В.",
            "gender" => "женский",
            "username" => "kuznetsovavv",
        ],
        [
            "firstName" => "Артем Андреевич",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов А.А.",
            "gender" => "мужской",
            "username" => "smirnovaa2",
        ],
        [
            "firstName" => "Надежда Васильевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.В.",
            "gender" => "женский",
            "username" => "novikovanv",
        ],
        [
            "firstName" => "Андрей Игоревич",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.И.",
            "gender" => "мужской",
            "username" => "kozlovai",
        ],
        [
            "firstName" => "Екатерина Васильевна",
            "lastName" => "Попова",
            "shortName" => "Попова Е.В.",
            "gender" => "женский",
            "username" => "popovaev",
        ],
        [
            "firstName" => "Даниил Александрович",
            "lastName" => "Соколов",
            "shortName" => "Соколов Д.А.",
            "gender" => "мужской",
            "username" => "sokolovda",
        ],
        [
            "firstName" => "Марина Александровна",
            "lastName" => "Федорова",
            "shortName" => "Федорова М.А.",
            "gender" => "женский",
            "username" => "fedorovama",
        ],
        [
            "firstName" => "Сергей Васильевич",
            "lastName" => "Иванов",
            "shortName" => "Иванов С.В.",
            "gender" => "мужской",
            "username" => "ivanovsv",
        ],
        [
            "firstName" => "Евгения Игоревна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.И.",
            "gender" => "женский",
            "username" => "kovalevaei",
        ],
        [
            "firstName" => "Дмитрий Сергеевич",
            "lastName" => "Петров",
            "shortName" => "Петров Д.С.",
            "gender" => "мужской",
            "username" => "petrovds",
        ],
        [
            "firstName" => "Екатерина Александровна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.А.",
            "gender" => "женский",
            "username" => "kuznetsovaea",
        ],
        [
            "firstName" => "Марина Владимировна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.В.",
            "gender" => "женский",
            "username" => "smirnovamv",
        ],
        [
            "firstName" => "Артём Игоревич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.И.",
            "gender" => "мужской",
            "username" => "kuznetsovai",
        ],
        [
            "firstName" => "Елизавета Сергеевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.С.",
            "gender" => "женский",
            "username" => "sokolovaes",
        ],
        [
            "firstName" => "Иван Фёдорович",
            "lastName" => "Иванов",
            "shortName" => "Иванов И.Ф.",
            "gender" => "мужской",
            "username" => "ivanovif",
        ],
        [
            "firstName" => "Анастасия Александровна",
            "lastName" => "Крылова",
            "shortName" => "Крылова А.А.",
            "gender" => "женский",
            "username" => "krylovaaa",
        ],
        [
            "firstName" => "Сергей Андреевич",
            "lastName" => "Попов",
            "shortName" => "Попов С.А.",
            "gender" => "мужской",
            "username" => "popovsa",
        ],
        [
            "firstName" => "Дарья Дмитриевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Д.Д.",
            "gender" => "женский",
            "username" => "novikovadd",
        ],
        [
            "firstName" => "Максим Владимирович",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.В.",
            "gender" => "мужской",
            "username" => "morozovmv",
        ],
        [
            "firstName" => "Алиса Ивановна",
            "lastName" => "Кузьмина",
            "shortName" => "Кузьмина А.И.",
            "gender" => "женский",
            "username" => "kuzminaai",
        ],
        [
            "firstName" => "Илья Сергеевич",
            "lastName" => "Куликов",
            "shortName" => "Куликов И.С.",
            "gender" => "мужской",
            "username" => "kulikovis",
        ],
        [
            "firstName" => "Анна Андреевна",
            "lastName" => "Николаева",
            "shortName" => "Николаева А.А.",
            "gender" => "женский",
            "username" => "nikolaevaaa",
        ],
        [
            "firstName" => "Андрей Павлович",
            "lastName" => "Жуков",
            "shortName" => "Жуков А.П.",
            "gender" => "мужской",
            "username" => "zhukovap",
        ],
        [
            "firstName" => "Екатерина Андреевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Е.А.",
            "gender" => "женский",
            "username" => "smirnovaea",
        ],
        [
            "firstName" => "Михаил Фёдорович",
            "lastName" => "Волков",
            "shortName" => "Волков М.Ф.",
            "gender" => "мужской",
            "username" => "volkovmf",
        ],
        [
            "firstName" => "Алина Игоревна",
            "lastName" => "Дмитриева",
            "shortName" => "Дмитриева А.И.",
            "gender" => "женский",
            "username" => "dmitrievaai",
        ],
        [
            "firstName" => "Денис Владимирович",
            "lastName" => "Ковалёв",
            "shortName" => "Ковалёв Д.В.",
            "gender" => "мужской",
            "username" => "kovaliovdv",
        ],
        [
            "firstName" => "Александра Сергеевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.С.",
            "gender" => "женский",
            "username" => "novikovaas",
        ],
        [
            "firstName" => "Владимир Александрович",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.А.",
            "gender" => "мужской",
            "username" => "sokolovva",
        ],
        [
            "firstName" => "Кристина Петровна",
            "lastName" => "Крылова",
            "shortName" => "Крылова К.П.",
            "gender" => "женский",
            "username" => "krylovakp",
        ],
        [
            "firstName" => "Екатерина Николаевна",
            "lastName" => "Андреева",
            "shortName" => "Андреева Е.Н.",
            "gender" => "женский",
            "username" => "andreevaen",
        ],
        [
            "firstName" => "Виктория Сергеевна",
            "lastName" => "Белова",
            "shortName" => "Белова В.С.",
            "gender" => "женский",
            "username" => "belovavs",
        ],
        [
            "firstName" => "Владислава Павловна",
            "lastName" => "Бурова",
            "shortName" => "Бурова В.П.",
            "gender" => "женский",
            "username" => "burovavp",
        ],
        [
            "firstName" => "Леонид Андреевич",
            "lastName" => "Волков",
            "shortName" => "Волков Л.А.",
            "gender" => "мужской",
            "username" => "volkovla",
        ],
        [
            "firstName" => "Антонина Александровна",
            "lastName" => "Герасимова",
            "shortName" => "Герасимова А.А.",
            "gender" => "женский",
            "username" => "gerasimovaaa",
        ],
        [
            "firstName" => "Михаил Иванович",
            "lastName" => "Гришин",
            "shortName" => "Гришин М.И.",
            "gender" => "мужской",
            "username" => "grishinmi",
        ],
        [
            "firstName" => "Ольга Денисовна",
            "lastName" => "Данилова",
            "shortName" => "Данилова О.Д.",
            "gender" => "женский",
            "username" => "danilovaod",
        ],
        [
            "firstName" => "Наталья Александровна",
            "lastName" => "Ефимова",
            "shortName" => "Ефимова Н.А.",
            "gender" => "женский",
            "username" => "efimovana",
        ],
        [
            "firstName" => "Сергей Дмитриевич",
            "lastName" => "Зайцев",
            "shortName" => "Зайцев С.Д.",
            "gender" => "мужской",
            "username" => "zaitsevsd",
        ],
        [
            "firstName" => "Евгений Викторович",
            "lastName" => "Козлов",
            "shortName" => "Козлов Е.В.",
            "gender" => "мужской",
            "username" => "kozlovev",
        ],
        [
            "firstName" => "Лилия Сергеевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Л.С.",
            "gender" => "женский",
            "username" => "kuznetsovals",
        ],
        [
            "firstName" => "Никита Андреевич",
            "lastName" => "Лебедев",
            "shortName" => "Лебедев Н.А.",
            "gender" => "мужской",
            "username" => "lebedevna",
        ],
        [
            "firstName" => "Василий Петрович",
            "lastName" => "Макаров",
            "shortName" => "Макаров В.П.",
            "gender" => "мужской",
            "username" => "makarovvp",
        ],
        [
            "firstName" => "Алиса Дмитриевна",
            "lastName" => "Маркова",
            "shortName" => "Маркова А.Д.",
            "gender" => "женский",
            "username" => "markovaad",
        ],
        [
            "firstName" => "Иван Александрович",
            "lastName" => "Николаев",
            "shortName" => "Николаев И.А.",
            "gender" => "мужской",
            "username" => "nikolaevia",
        ],
        [
            "firstName" => "Татьяна Валерьевна",
            "lastName" => "Орлова",
            "shortName" => "Орлова Т.В.",
            "gender" => "женский",
            "username" => "orlovatv",
        ],
        [
            "firstName" => "Антон Игоревич",
            "lastName" => "Павлов",
            "shortName" => "Павлов А.И.",
            "gender" => "мужской",
            "username" => "pavlovai",
        ],
        [
            "firstName" => "Александра Валерьевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова А.В.",
            "gender" => "женский",
            "username" => "petrovaav",
        ],
        [
            "firstName" => "Александра Викторовна",
            "lastName" => "Андреева",
            "shortName" => "Андреева А.В.",
            "gender" => "женский",
            "username" => "andreevaav",
        ],
        [
            "firstName" => "Иван Михайлович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.М.",
            "gender" => "мужской",
            "username" => "smirnovim",
        ],
        [
            "firstName" => "Ольга Алексеевна",
            "lastName" => "Попова",
            "shortName" => "Попова О.А.",
            "gender" => "женский",
            "username" => "popovaoa",
        ],
        [
            "firstName" => "Андрей Игоревич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.И.",
            "gender" => "мужской",
            "username" => "kuznetsovai2",
        ],
        [
            "firstName" => "Екатерина Анатольевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.А.",
            "gender" => "женский",
            "username" => "fedorovaea",
        ],
        [
            "firstName" => "Дмитрий Сергеевич",
            "lastName" => "Морозов",
            "shortName" => "Морозов Д.С.",
            "gender" => "мужской",
            "username" => "morozovds",
        ],
        [
            "firstName" => "Анна Владимировна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.В.",
            "gender" => "женский",
            "username" => "novikovaav2",
        ],
        [
            "firstName" => "Сергей Александрович",
            "lastName" => "Волков",
            "shortName" => "Волков С.А.",
            "gender" => "мужской",
            "username" => "volkovsa",
        ],
        [
            "firstName" => "Татьяна Васильевна",
            "lastName" => "Андреева",
            "shortName" => "Андреева Т.В.",
            "gender" => "женский",
            "username" => "andreevatv",
        ],
        [
            "firstName" => "Владимир Иванович",
            "lastName" => "Петров",
            "shortName" => "Петров В.И.",
            "gender" => "мужской",
            "username" => "petrovvi",
        ],
        [
            "firstName" => "Елена Игоревна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.И.",
            "gender" => "женский",
            "username" => "sokolovaei",
        ],
        [
            "firstName" => "Николай Павлович",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев Н.П.",
            "gender" => "мужской",
            "username" => "kovalevnp",
        ],
        [
            "firstName" => "Марина Владимировна",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева М.В.",
            "gender" => "женский",
            "username" => "lebedevamv",
        ],
        [
            "firstName" => "Алексей Андреевич",
            "lastName" => "Семенов",
            "shortName" => "Семенов А.А.",
            "gender" => "мужской",
            "username" => "semenovaa",
        ],
        [
            "firstName" => "Ирина Дмитриевна",
            "lastName" => "Егорова",
            "shortName" => "Егорова И.Д.",
            "gender" => "женский",
            "username" => "egorovaid",
        ],
        [
            "firstName" => "Виктория Сергеевна",
            "lastName" => "Павлова",
            "shortName" => "Павлова В.С.",
            "gender" => "женский",
            "username" => "pavlovavs",
        ],
        [
            "firstName" => "Роман Александрович",
            "lastName" => "Васильев",
            "shortName" => "Васильев Р.А.",
            "gender" => "мужской",
            "username" => "vasilevra",
        ],
        [
            "firstName" => "Никита Сергеевич",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Н.С.",
            "gender" => "мужской",
            "username" => "smirnovns",
        ],
        [
            "firstName" => "Ольга Павловна",
            "lastName" => "Иванова",
            "shortName" => "Иванова О.П.",
            "gender" => "женский",
            "username" => "ivanovaop",
        ],
        [
            "firstName" => "Александр Дмитриевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.Д.",
            "gender" => "мужской",
            "username" => "kuznetsovad",
        ],
        [
            "firstName" => "Ирина Андреевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова И.А.",
            "gender" => "женский",
            "username" => "sokolovaia",
        ],
        [
            "firstName" => "Дмитрий Владимирович",
            "lastName" => "Попов",
            "shortName" => "Попов Д.В.",
            "gender" => "мужской",
            "username" => "popovdv2",
        ],
        [
            "firstName" => "Елена Михайловна",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева Е.М.",
            "gender" => "женский",
            "username" => "lebedevaem",
        ],
        [
            "firstName" => "Андрей Александрович",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.А.",
            "gender" => "мужской",
            "username" => "kozlovaa2",
        ],
        [
            "firstName" => "Ольга Владимировна",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.В.",
            "gender" => "женский",
            "username" => "novikovaov",
        ],
        [
            "firstName" => "Максим Алексеевич",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.А.",
            "gender" => "мужской",
            "username" => "morozovma",
        ],
        [
            "firstName" => "Екатерина Ивановна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.И.",
            "gender" => "женский",
            "username" => "petrovaei",
        ],
        [
            "firstName" => "Алексей Анатольевич",
            "lastName" => "Волков",
            "shortName" => "Волков А.А.",
            "gender" => "мужской",
            "username" => "volkovaa",
        ],
        [
            "firstName" => "Юлия Андреевна",
            "lastName" => "Соловьева",
            "shortName" => "Соловьева Ю.А.",
            "gender" => "женский",
            "username" => "solovevaiua",
        ],
        [
            "firstName" => "Сергей Викторович",
            "lastName" => "Васильев",
            "shortName" => "Васильев С.В.",
            "gender" => "мужской",
            "username" => "vasilevsv",
        ],
        [
            "firstName" => "Надежда Александровна",
            "lastName" => "Зайцева",
            "shortName" => "Зайцева Н.А.",
            "gender" => "женский",
            "username" => "zaitsevana",
        ],
        [
            "firstName" => "Антон Игоревич",
            "lastName" => "Павлов",
            "shortName" => "Павлов А.И.",
            "gender" => "мужской",
            "username" => "pavlovai2",
        ],
        [
            "firstName" => "Татьяна Сергеевна",
            "lastName" => "Семенова",
            "shortName" => "Семенова Т.С.",
            "gender" => "женский",
            "username" => "semenovats",
        ],
        [
            "firstName" => "Александр Анатольевич",
            "lastName" => "Григорьев",
            "shortName" => "Григорьев А.А.",
            "gender" => "мужской",
            "username" => "grigorevaa",
        ],
        [
            "firstName" => "Ирина Дмитриевна",
            "lastName" => "Богданова",
            "shortName" => "Богданова И.Д.",
            "gender" => "женский",
            "username" => "bogdanovaid",
        ],
        [
            "firstName" => "Екатерина Ивановна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.И.",
            "gender" => "женский",
            "username" => "kuznetsovaei",
        ],
        [
            "firstName" => "Андрей Александрович",
            "lastName" => "Попов",
            "shortName" => "Попов А.А.",
            "gender" => "мужской",
            "username" => "popovaa",
        ],
        [
            "firstName" => "Ольга Сергеевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева О.С.",
            "gender" => "женский",
            "username" => "kovalevaos",
        ],
        [
            "firstName" => "Владислав Николаевич",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов В.Н.",
            "gender" => "мужской",
            "username" => "smirnovvn",
        ],
        [
            "firstName" => "Надежда Владимировна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Н.В.",
            "gender" => "женский",
            "username" => "ivanovanv",
        ],
        [
            "firstName" => "Максим Игоревич",
            "lastName" => "Соколов",
            "shortName" => "Соколов М.И.",
            "gender" => "мужской",
            "username" => "sokolovmi",
        ],
        [
            "firstName" => "Ирина Александровна",
            "lastName" => "Кузьмина",
            "shortName" => "Кузьмина И.А.",
            "gender" => "женский",
            "username" => "kuzminaia",
        ],
        [
            "firstName" => "Артем Сергеевич",
            "lastName" => "Медведев",
            "shortName" => "Медведев А.С.",
            "gender" => "мужской",
            "username" => "medvedevas",
        ],
        [
            "firstName" => "Людмила Васильевна",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева Л.В.",
            "gender" => "женский",
            "username" => "lebedevalv",
        ],
        [
            "firstName" => "Денис Иванович",
            "lastName" => "Николаев",
            "shortName" => "Николаев Д.И.",
            "gender" => "мужской",
            "username" => "nikolaevdi",
        ],
        [
            "firstName" => "Мария Степановна",
            "lastName" => "Волкова",
            "shortName" => "Волкова М.С.",
            "gender" => "женский",
            "username" => "volkovams",
        ],
        [
            "firstName" => "Антон Андреевич",
            "lastName" => "Кузьмин",
            "shortName" => "Кузьмин А.А.",
            "gender" => "мужской",
            "username" => "kuzminaa",
        ],
        [
            "firstName" => "Екатерина Владимировна",
            "lastName" => "Сидорова",
            "shortName" => "Сидорова Е.В.",
            "gender" => "женский",
            "username" => "sidorovaev",
        ],
        [
            "firstName" => "Роман Иванович",
            "lastName" => "Петров",
            "shortName" => "Петров Р.И.",
            "gender" => "мужской",
            "username" => "petrovri",
        ],
        [
            "firstName" => "Ирина Дмитриевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.Д.",
            "gender" => "женский",
            "username" => "fedorovaid",
        ],
        [
            "firstName" => "Владислав Анатольевич",
            "lastName" => "Комаров",
            "shortName" => "Комаров В.А.",
            "gender" => "мужской",
            "username" => "komarovva",
        ],
        [
            "firstName" => "Оксана Ивановна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова О.И.",
            "gender" => "женский",
            "username" => "kuznetsovaoi",
        ],
        [
            "firstName" => "Сергей Игоревич",
            "lastName" => "Белов",
            "shortName" => "Белов С.И.",
            "gender" => "мужской",
            "username" => "belovsi",
        ],
        [
            "firstName" => "Анастасия Александровна",
            "lastName" => "Соловьева",
            "shortName" => "Соловьева А.А.",
            "gender" => "женский",
            "username" => "solovevaaa",
        ],
        [
            "firstName" => "Ксения Дмитриевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева К.Д.",
            "gender" => "женский",
            "username" => "kovalevakd",
        ],
        [
            "firstName" => "Владимир Игоревич",
            "lastName" => "Белов",
            "shortName" => "Белов В.И.",
            "gender" => "мужской",
            "username" => "belovvi",
        ],
        [
            "firstName" => "Нина Александровна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Н.А.",
            "gender" => "женский",
            "username" => "smirnovana",
        ],
        [
            "firstName" => "Артем Сергеевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.С.",
            "gender" => "мужской",
            "username" => "kuznetsovas",
        ],
        [
            "firstName" => "Дарья Александровна",
            "lastName" => "Попова",
            "shortName" => "Попова Д.А.",
            "gender" => "женский",
            "username" => "popovada",
        ],
        [
            "firstName" => "Андрей Владимирович",
            "lastName" => "Михайлов",
            "shortName" => "Михайлов А.В.",
            "gender" => "мужской",
            "username" => "mikhailovav",
        ],
        [
            "firstName" => "Марина Александровна",
            "lastName" => "Соловьева",
            "shortName" => "Соловьева М.А.",
            "gender" => "женский",
            "username" => "solovevama",
        ],
        [
            "firstName" => "Игорь Александрович",
            "lastName" => "Новиков",
            "shortName" => "Новиков И.А.",
            "gender" => "мужской",
            "username" => "novikovia",
        ],
        [
            "firstName" => "Елена Дмитриевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.Д.",
            "gender" => "женский",
            "username" => "petrovaed",
        ],
        [
            "firstName" => "Константин Ильич",
            "lastName" => "Андреев",
            "shortName" => "Андреев К.И.",
            "gender" => "мужской",
            "username" => "andreevki",
        ],
        [
            "firstName" => "Ольга Владимировна",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева О.В.",
            "gender" => "женский",
            "username" => "lebedevaov",
        ],
        [
            "firstName" => "Валентина Петровна",
            "lastName" => "Егорова",
            "shortName" => "Егорова В.П.",
            "gender" => "женский",
            "username" => "egorovavp",
        ],
    ];

    const STUDENTS = [
        [
            "firstName" => "Елена Дмитриевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Е.Д.",
            "gender" => "женский",
            "username" => "ivanovaed",
        ],
        [
            "firstName" => "Игорь Александрович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.А.",
            "gender" => "мужской",
            "username" => "smirnovia",
        ],
        [
            "firstName" => "Анна Владимировна",
            "lastName" => "Петрова",
            "shortName" => "Петрова А.В.",
            "gender" => "женский",
            "username" => "petrovaav",
        ],
        [
            "firstName" => "Сергей Васильевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов С.В.",
            "gender" => "мужской",
            "username" => "kuznetsovsv",
        ],
        [
            "firstName" => "Надежда Ивановна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Н.И.",
            "gender" => "женский",
            "username" => "morozovani",
        ],
        [
            "firstName" => "Петр Николаевич",
            "lastName" => "Васильев",
            "shortName" => "Васильев П.Н.",
            "gender" => "мужской",
            "username" => "vasilevpn",
        ],
        [
            "firstName" => "Татьяна Сергеевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Т.С.",
            "gender" => "женский",
            "username" => "kovalevats",
        ],
        [
            "firstName" => "Илья Павлович",
            "lastName" => "Новиков",
            "shortName" => "Новиков И.П.",
            "gender" => "мужской",
            "username" => "novikovip",
        ],
        [
            "firstName" => "Екатерина Александровна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.А.",
            "gender" => "женский",
            "username" => "sokolovaea",
        ],
        [
            "firstName" => "Андрей Викторович",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.В.",
            "gender" => "мужской",
            "username" => "kozlovav",
        ],
        [
            "firstName" => "Ольга Васильевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова О.В.",
            "gender" => "женский",
            "username" => "fedorovaov",
        ],
        [
            "firstName" => "Дмитрий Сергеевич",
            "lastName" => "Ильин",
            "shortName" => "Ильин Д.С.",
            "gender" => "мужской",
            "username" => "ilinds",
        ],
        [
            "firstName" => "Анастасия Андреевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.А.",
            "gender" => "женский",
            "username" => "smirnovaaa",
        ],
        [
            "firstName" => "Владимир Владимирович",
            "lastName" => "Петров",
            "shortName" => "Петров В.В.",
            "gender" => "мужской",
            "username" => "petrovvv",
        ],
        [
            "firstName" => "Алина Сергеевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова А.С.",
            "gender" => "женский",
            "username" => "kuznetsovaas",
        ],
        [
            "firstName" => "Георгий Иванович",
            "lastName" => "Морозов",
            "shortName" => "Морозов Г.И.",
            "gender" => "мужской",
            "username" => "morozovgi",
        ],
        [
            "firstName" => "Елена Дмитриевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Е.Д.",
            "gender" => "женский",
            "username" => "vasilevaed",
        ],
        [
            "firstName" => "Иван Владимирович",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев И.В.",
            "gender" => "мужской",
            "username" => "kovaleviv",
        ],
        [
            "firstName" => "Александра Павловна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.П.",
            "gender" => "женский",
            "username" => "novikovaap",
        ],
        [
            "firstName" => "Максим Александрович",
            "lastName" => "Соколов",
            "shortName" => "Соколов М.А.",
            "gender" => "мужской",
            "username" => "sokolovma",
        ],
        [
            "firstName" => "Артем Сергеевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.С.",
            "gender" => "мужской",
            "username" => "fedorovas",
        ],
        [
            "firstName" => "Анастасия Дмитриевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.Д.",
            "gender" => "женский",
            "username" => "ivanovaad",
        ],
        [
            "firstName" => "Денис Андреевич",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Д.А.",
            "gender" => "мужской",
            "username" => "smirnovda",
        ],
        [
            "firstName" => "Софья Владимировна",
            "lastName" => "Петрова",
            "shortName" => "Петрова С.В.",
            "gender" => "женский",
            "username" => "petrovasv",
        ],
        [
            "firstName" => "Владислав Васильевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов В.В.",
            "gender" => "мужской",
            "username" => "kuznetsovvv",
        ],
        [
            "firstName" => "Людмила Ивановна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Л.И.",
            "gender" => "женский",
            "username" => "morozovali",
        ],
        [
            "firstName" => "Николай Николаевич",
            "lastName" => "Васильев",
            "shortName" => "Васильев Н.Н.",
            "gender" => "мужской",
            "username" => "vasilevnn",
        ],
        [
            "firstName" => "Анастасия Сергеевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.С.",
            "gender" => "женский",
            "username" => "kovalevaas",
        ],
        [
            "firstName" => "Дмитрий Викторович",
            "lastName" => "Новиков",
            "shortName" => "Новиков Д.В.",
            "gender" => "мужской",
            "username" => "novikovdv",
        ],
        [
            "firstName" => "Александра Александровна",
            "lastName" => "Соколова",
            "shortName" => "Соколова А.А.",
            "gender" => "женский",
            "username" => "sokolovaaa",
        ],
        [
            "firstName" => "Илья Петрович",
            "lastName" => "Козлов",
            "shortName" => "Козлов И.П.",
            "gender" => "мужской",
            "username" => "kozlovip",
        ],
        [
            "firstName" => "Елизавета Сергеевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.С.",
            "gender" => "женский",
            "username" => "fedorovaes",
        ],
        [
            "firstName" => "Андрей Дмитриевич",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.Д.",
            "gender" => "мужской",
            "username" => "ivanovad",
        ],
        [
            "firstName" => "Мария Андреевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.А.",
            "gender" => "женский",
            "username" => "smirnovama",
        ],
        [
            "firstName" => "Сергей Викторович",
            "lastName" => "Петров",
            "shortName" => "Петров С.В.",
            "gender" => "мужской",
            "username" => "petrovsv",
        ],
        [
            "firstName" => "Екатерина Николаевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.Н.",
            "gender" => "женский",
            "username" => "kuznetsovaen",
        ],
        [
            "firstName" => "Игорь Иванович",
            "lastName" => "Морозов",
            "shortName" => "Морозов И.И.",
            "gender" => "мужской",
            "username" => "morozovii",
        ],
        [
            "firstName" => "Наталья Дмитриевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.Д.",
            "gender" => "женский",
            "username" => "vasilevand",
        ],
        [
            "firstName" => "Павел Александрович",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев П.А.",
            "gender" => "мужской",
            "username" => "kovalevpa",
        ],
        [
            "firstName" => "Екатерина Павловна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.П.",
            "gender" => "женский",
            "username" => "novikovaep",
        ],
        [
            "firstName" => "Владислав Андреевич",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.А.",
            "gender" => "мужской",
            "username" => "sokolovva",
        ],
        [
            "firstName" => "Александра Дмитриевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.Д.",
            "gender" => "женский",
            "username" => "kozlovaad",
        ],
        [
            "firstName" => "Максим Сергеевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров М.С.",
            "gender" => "мужской",
            "username" => "fedorovms",
        ],
        [
            "firstName" => "Анна Андреевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.А.",
            "gender" => "женский",
            "username" => "ivanovaaa",
        ],
        [
            "firstName" => "Георгий Петрович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Г.П.",
            "gender" => "мужской",
            "username" => "smirnovgp",
        ],
        [
            "firstName" => "Марина Владимировна",
            "lastName" => "Петрова",
            "shortName" => "Петрова М.В.",
            "gender" => "женский",
            "username" => "petrovamv",
        ],
        [
            "firstName" => "Иван Анатольевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов И.А.",
            "gender" => "мужской",
            "username" => "kuznetsovia",
        ],
        [
            "firstName" => "Надежда Ивановна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Н.И.",
            "gender" => "женский",
            "username" => "morozovani2",
        ],
        [
            "firstName" => "Дмитрий Николаевич",
            "lastName" => "Васильев",
            "shortName" => "Васильев Д.Н.",
            "gender" => "мужской",
            "username" => "vasilevdn",
        ],
        [
            "firstName" => "Анна Сергеевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.С.",
            "gender" => "женский",
            "username" => "kovalevaas2",
        ],
        [
            "firstName" => "Андрей Викторович",
            "lastName" => "Новиков",
            "shortName" => "Новиков А.В.",
            "gender" => "мужской",
            "username" => "novikovav",
        ],
        [
            "firstName" => "Екатерина Александровна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.А.",
            "gender" => "женский",
            "username" => "sokolovaea2",
        ],
        [
            "firstName" => "Степан Александрович",
            "lastName" => "Козлов",
            "shortName" => "Козлов С.А.",
            "gender" => "мужской",
            "username" => "kozlovsa",
        ],
        [
            "firstName" => "Екатерина Владимировна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.В.",
            "gender" => "женский",
            "username" => "fedorovaev",
        ],
        [
            "firstName" => "Алексей Андреевич",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.А.",
            "gender" => "мужской",
            "username" => "ivanovaa",
        ],
        [
            "firstName" => "Мария Викторовна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.В.",
            "gender" => "женский",
            "username" => "smirnovamv",
        ],
        [
            "firstName" => "Сергей Петрович",
            "lastName" => "Петров",
            "shortName" => "Петров С.П.",
            "gender" => "мужской",
            "username" => "petrovsp",
        ],
        [
            "firstName" => "Дарья Николаевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Д.Н.",
            "gender" => "женский",
            "username" => "kuznetsovadn",
        ],
        [
            "firstName" => "Михаил Иванович",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.И.",
            "gender" => "мужской",
            "username" => "morozovmi",
        ],
        [
            "firstName" => "Анна Дмитриевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева А.Д.",
            "gender" => "женский",
            "username" => "vasilevaad",
        ],
        [
            "firstName" => "Василий Павлович",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев В.П.",
            "gender" => "мужской",
            "username" => "kovalevvp",
        ],
        [
            "firstName" => "Алина Александровна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.А.",
            "gender" => "женский",
            "username" => "novikovaaa",
        ],
        [
            "firstName" => "Илья Андреевич",
            "lastName" => "Соколов",
            "shortName" => "Соколов И.А.",
            "gender" => "мужской",
            "username" => "sokolovia",
        ],
        [
            "firstName" => "Маргарита Дмитриевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова М.Д.",
            "gender" => "женский",
            "username" => "kozlovamd",
        ],
        [
            "firstName" => "Алексей Сергеевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.С.",
            "gender" => "мужской",
            "username" => "fedorovas2",
        ],
        [
            "firstName" => "Лидия Владимировна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Л.В.",
            "gender" => "женский",
            "username" => "ivanovalv",
        ],
        [
            "firstName" => "Даниил Викторович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Д.В.",
            "gender" => "мужской",
            "username" => "smirnovdv",
        ],
        [
            "firstName" => "Софья Андреевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова С.А.",
            "gender" => "женский",
            "username" => "petrovasa",
        ],
        [
            "firstName" => "Валерия Игоревна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова В.И.",
            "gender" => "женский",
            "username" => "kuznetsovavi",
        ],
        [
            "firstName" => "Матвей Николаевич",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.Н.",
            "gender" => "мужской",
            "username" => "morozovmn",
        ],
        [
            "firstName" => "Анастасия Владимировна",
            "lastName" => "Васильева",
            "shortName" => "Васильева А.В.",
            "gender" => "женский",
            "username" => "vasilevaav",
        ],
        [
            "firstName" => "Артем Анатольевич",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев А.А.",
            "gender" => "мужской",
            "username" => "kovalevaa",
        ],
        [
            "firstName" => "Ольга Игоревна",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.И.",
            "gender" => "женский",
            "username" => "novikovaoi",
        ],
        [
            "firstName" => "Владимир Сергеевич",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.С.",
            "gender" => "мужской",
            "username" => "sokolovvs",
        ],
        [
            "firstName" => "Юлия Александровна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Ю.А.",
            "gender" => "женский",
            "username" => "kozlovaiua",
        ],
        [
            "firstName" => "Илья Васильевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров И.В.",
            "gender" => "мужской",
            "username" => "fedoroviv",
        ],
        [
            "firstName" => "Вероника Анатольевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова В.А.",
            "gender" => "женский",
            "username" => "ivanovava",
        ],
        [
            "firstName" => "Антон Сергеевич",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов А.С.",
            "gender" => "мужской",
            "username" => "smirnovas",
        ],
        [
            "firstName" => "Ольга Петровна",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.П.",
            "gender" => "женский",
            "username" => "petrovaop",
        ],
        [
            "firstName" => "Дмитрий Викторович",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов Д.В.",
            "gender" => "мужской",
            "username" => "kuznetsovdv",
        ],
        [
            "firstName" => "Елена Анатольевна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.А.",
            "gender" => "женский",
            "username" => "morozovaea",
        ],
        [
            "firstName" => "Иван Александрович",
            "lastName" => "Васильев",
            "shortName" => "Васильев И.А.",
            "gender" => "мужской",
            "username" => "vasilevia",
        ],
        [
            "firstName" => "Екатерина Викторовна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.В.",
            "gender" => "женский",
            "username" => "kovalevaev",
        ],
        [
            "firstName" => "Павел Сергеевич",
            "lastName" => "Новиков",
            "shortName" => "Новиков П.С.",
            "gender" => "мужской",
            "username" => "novikovps",
        ],
        [
            "firstName" => "Марина Валерьевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.В.",
            "gender" => "женский",
            "username" => "sokolovamv",
        ],
        [
            "firstName" => "Артемий Александрович",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.А.",
            "gender" => "мужской",
            "username" => "kozlovaa",
        ],
        [
            "firstName" => "Оксана Ильинична",
            "lastName" => "Федорова",
            "shortName" => "Федорова О.И.",
            "gender" => "женский",
            "username" => "fedorovaoi",
        ],
        [
            "firstName" => "Михаил Викторович",
            "lastName" => "Иванов",
            "shortName" => "Иванов М.В.",
            "gender" => "мужской",
            "username" => "ivanovmv",
        ],
        [
            "firstName" => "Анастасия Владимировна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.В.",
            "gender" => "женский",
            "username" => "smirnovaav",
        ],
        [
            "firstName" => "Вадим Андреевич",
            "lastName" => "Петров",
            "shortName" => "Петров В.А.",
            "gender" => "мужской",
            "username" => "petrovva",
        ],
        [
            "firstName" => "Ирина Владимировна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова И.В.",
            "gender" => "женский",
            "username" => "kuznetsovaiv",
        ],
        [
            "firstName" => "Константин Николаевич",
            "lastName" => "Морозов",
            "shortName" => "Морозов К.Н.",
            "gender" => "мужской",
            "username" => "morozovkn",
        ],
        [
            "firstName" => "Светлана Анатольевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева С.А.",
            "gender" => "женский",
            "username" => "vasilevasa",
        ],
        [
            "firstName" => "Андрей Викторович",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев А.В.",
            "gender" => "мужской",
            "username" => "kovalevav",
        ],
        [
            "firstName" => "Евгения Павловна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.П.",
            "gender" => "женский",
            "username" => "novikovaep2",
        ],
        [
            "firstName" => "Никита Андреевич",
            "lastName" => "Соколов",
            "shortName" => "Соколов Н.А.",
            "gender" => "мужской",
            "username" => "sokolovna",
        ],
        [
            "firstName" => "Алиса Александровна",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.А.",
            "gender" => "женский",
            "username" => "kozlovaaa",
        ],
        [
            "firstName" => "Георгий Сергеевич",
            "lastName" => "Федоров",
            "shortName" => "Федоров Г.С.",
            "gender" => "мужской",
            "username" => "fedorovgs",
        ],
        [
            "firstName" => "Анастасия Александровна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.А.",
            "gender" => "женский",
            "username" => "ivanovaaa2",
        ],
        [
            "firstName" => "Денис Васильевич",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Д.В.",
            "gender" => "мужской",
            "username" => "smirnovdv2",
        ],
        [
            "firstName" => "Елена Игоревна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.И.",
            "gender" => "женский",
            "username" => "petrovaei",
        ],
        [
            "firstName" => "Антонина Александровна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова А.А.",
            "gender" => "женский",
            "username" => "kuznetsovaaa",
        ],
        [
            "firstName" => "Роман Викторович",
            "lastName" => "Морозов",
            "shortName" => "Морозов Р.В.",
            "gender" => "мужской",
            "username" => "morozovrv",
        ],
        [
            "firstName" => "Ирина Васильевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева И.В.",
            "gender" => "женский",
            "username" => "vasilevaiv",
        ],
        [
            "firstName" => "Александр Владимирович",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев А.В.",
            "gender" => "мужской",
            "username" => "kovalevav2",
        ],
        [
            "firstName" => "Ольга Павловна",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.П.",
            "gender" => "женский",
            "username" => "novikovaop",
        ],
        [
            "firstName" => "Сергей Игоревич",
            "lastName" => "Соколов",
            "shortName" => "Соколов С.И.",
            "gender" => "мужской",
            "username" => "sokolovsi",
        ],
        [
            "firstName" => "Маргарита Александровна",
            "lastName" => "Козлова",
            "shortName" => "Козлова М.А.",
            "gender" => "женский",
            "username" => "kozlovama",
        ],
        [
            "firstName" => "Анатолий Владимирович",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.В.",
            "gender" => "мужской",
            "username" => "fedorovav",
        ],
        [
            "firstName" => "Вера Ивановна",
            "lastName" => "Иванова",
            "shortName" => "Иванова В.И.",
            "gender" => "женский",
            "username" => "ivanovavi",
        ],
        [
            "firstName" => "Игорь Викторович",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.В.",
            "gender" => "мужской",
            "username" => "smirnoviv",
        ],
        [
            "firstName" => "Ольга Владимировна",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.В.",
            "gender" => "женский",
            "username" => "petrovaov",
        ],
        [
            "firstName" => "Владимир Андреевич",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов В.А.",
            "gender" => "мужской",
            "username" => "kuznetsovva",
        ],
        [
            "firstName" => "Марина Александровна",
            "lastName" => "Морозова",
            "shortName" => "Морозова М.А.",
            "gender" => "женский",
            "username" => "morozovama",
        ],
        [
            "firstName" => "Артем Васильевич",
            "lastName" => "Васильев",
            "shortName" => "Васильев А.В.",
            "gender" => "мужской",
            "username" => "vasilevav",
        ],
        [
            "firstName" => "Евгения Владимировна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.В.",
            "gender" => "женский",
            "username" => "kovalevaev2",
        ],
        [
            "firstName" => "Артемий Павлович",
            "lastName" => "Новиков",
            "shortName" => "Новиков А.П.",
            "gender" => "мужской",
            "username" => "novikovap",
        ],
        [
            "firstName" => "Елизавета Николаевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.Н.",
            "gender" => "женский",
            "username" => "sokolovaen",
        ],
        [
            "firstName" => "Виталий Владимирович",
            "lastName" => "Козлов",
            "shortName" => "Козлов В.В.",
            "gender" => "мужской",
            "username" => "kozlovvv",
        ],
        [
            "firstName" => "Ирина Александровна",
            "lastName" => "Попова",
            "shortName" => "Попова И.А.",
            "gender" => "женский",
            "username" => "popovaia",
        ],
    ];

    const PARENTS = [
        [
            "firstName" => "Ольга Владимировна",
            "lastName" => "Иванова",
            "shortName" => "Иванова О.В.",
            "gender" => "женский",
            "username" => "ivanovaov",
        ],
        [
            "firstName" => "Наталья Сергеевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Н.С.",
            "gender" => "женский",
            "username" => "smirnovans",
        ],
        [
            "firstName" => "Елена Ивановна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.И.",
            "gender" => "женский",
            "username" => "petrovaei",
        ],
        [
            "firstName" => "Евгения Ивановна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.И.",
            "gender" => "женский",
            "username" => "kuznetsovaei",
        ],
        [
            "firstName" => "Анна Александровна",
            "lastName" => "Морозова",
            "shortName" => "Морозова А.А.",
            "gender" => "женский",
            "username" => "morozovaaa",
        ],
        [
            "firstName" => "Мария Александровна",
            "lastName" => "Васильева",
            "shortName" => "Васильева М.А.",
            "gender" => "женский",
            "username" => "vasilevama",
        ],
        [
            "firstName" => "Оксана Владимировна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева О.В.",
            "gender" => "женский",
            "username" => "kovalevaov",
        ],
        [
            "firstName" => "Людмила Викторовна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Л.В.",
            "gender" => "женский",
            "username" => "novikovalv",
        ],
        [
            "firstName" => "Ирина Валерьевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова И.В.",
            "gender" => "женский",
            "username" => "sokolovaiv",
        ],
        [
            "firstName" => "Татьяна Сергеевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Т.С.",
            "gender" => "женский",
            "username" => "kozlovats",
        ],
        [
            "firstName" => "Елена Александровна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.А.",
            "gender" => "женский",
            "username" => "fedorovaea",
        ],
        [
            "firstName" => "Евгения Петровна",
            "lastName" => "Ильина",
            "shortName" => "Ильина Е.П.",
            "gender" => "женский",
            "username" => "ilinaep",
        ],
        [
            "firstName" => "Лариса Сергеевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Л.С.",
            "gender" => "женский",
            "username" => "smirnovals",
        ],
        [
            "firstName" => "Оксана Владимировна",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.В.",
            "gender" => "женский",
            "username" => "petrovaov",
        ],
        [
            "firstName" => "Татьяна Александровна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.А.",
            "gender" => "женский",
            "username" => "kuznetsovata",
        ],
        [
            "firstName" => "Елена Викторовна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.В.",
            "gender" => "женский",
            "username" => "morozovaev",
        ],
        [
            "firstName" => "Нина Николаевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.Н.",
            "gender" => "женский",
            "username" => "vasilevann",
        ],
        [
            "firstName" => "Надежда Андреевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.А.",
            "gender" => "женский",
            "username" => "kovalevana",
        ],
        [
            "firstName" => "Ольга Викторовна",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.В.",
            "gender" => "женский",
            "username" => "novikovaov",
        ],
        [
            "firstName" => "Алла Владимировна",
            "lastName" => "Соколова",
            "shortName" => "Соколова А.В.",
            "gender" => "женский",
            "username" => "sokolovaav",
        ],
        [
            "firstName" => "Ирина Анатольевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.А.",
            "gender" => "женский",
            "username" => "fedorovaia",
        ],
        [
            "firstName" => "Марина Викторовна",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.В.",
            "gender" => "женский",
            "username" => "ivanovamv",
        ],
        [
            "firstName" => "Лидия Петровна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Л.П.",
            "gender" => "женский",
            "username" => "smirnovalp",
        ],
        [
            "firstName" => "Евгения Викторовна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.В.",
            "gender" => "женский",
            "username" => "petrovaev",
        ],
        [
            "firstName" => "Анна Ивановна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова А.И.",
            "gender" => "женский",
            "username" => "kuznetsovaai",
        ],
        [
            "firstName" => "Евгения Владимировна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.В.",
            "gender" => "женский",
            "username" => "morozovaev2",
        ],
        [
            "firstName" => "Наталья Степановна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.С.",
            "gender" => "женский",
            "username" => "vasilevans",
        ],
        [
            "firstName" => "Наталья Николаевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.Н.",
            "gender" => "женский",
            "username" => "kovalevann",
        ],
        [
            "firstName" => "Елена Сергеевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.С.",
            "gender" => "женский",
            "username" => "novikovaes",
        ],
        [
            "firstName" => "Ирина Николаевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова И.Н.",
            "gender" => "женский",
            "username" => "sokolovain",
        ],
        [
            "firstName" => "Мария Александровна",
            "lastName" => "Козлова",
            "shortName" => "Козлова М.А.",
            "gender" => "женский",
            "username" => "kozlovama",
        ],
        [
            "firstName" => "Людмила Ивановна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Л.И.",
            "gender" => "женский",
            "username" => "fedorovali",
        ],
        [
            "firstName" => "Марина Ивановна",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.И.",
            "gender" => "женский",
            "username" => "ivanovami",
        ],
        [
            "firstName" => "Анна Андреевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.А.",
            "gender" => "женский",
            "username" => "smirnovaaa",
        ],
        [
            "firstName" => "Нина Александровна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Н.А.",
            "gender" => "женский",
            "username" => "petrovana",
        ],
        [
            "firstName" => "Елена Петровна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.П.",
            "gender" => "женский",
            "username" => "kuznetsovaep",
        ],
        [
            "firstName" => "Елена Анатольевна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.А.",
            "gender" => "женский",
            "username" => "morozovaea",
        ],
        [
            "firstName" => "Оксана Павловна",
            "lastName" => "Васильева",
            "shortName" => "Васильева О.П.",
            "gender" => "женский",
            "username" => "vasilevaop",
        ],
        [
            "firstName" => "Ирина Петровна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева И.П.",
            "gender" => "женский",
            "username" => "kovalevaip",
        ],
        [
            "firstName" => "Татьяна Владимировна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Т.В.",
            "gender" => "женский",
            "username" => "novikovatv",
        ],
        [
            "firstName" => "Наталья Игоревна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Н.И.",
            "gender" => "женский",
            "username" => "sokolovani",
        ],
        [
            "firstName" => "Елена Андреевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.А.",
            "gender" => "женский",
            "username" => "kozlovaea",
        ],
        [
            "firstName" => "Татьяна Александровна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Т.А.",
            "gender" => "женский",
            "username" => "fedorovata",
        ],
        [
            "firstName" => "Екатерина Владимировна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Е.В.",
            "gender" => "женский",
            "username" => "ivanovaev",
        ],
        [
            "firstName" => "Марина Сергеевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.С.",
            "gender" => "женский",
            "username" => "smirnovams",
        ],
        [
            "firstName" => "Александра Александровна",
            "lastName" => "Петрова",
            "shortName" => "Петрова А.А.",
            "gender" => "женский",
            "username" => "petrovaaa",
        ],
        [
            "firstName" => "Наталья Михайловна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Н.М.",
            "gender" => "женский",
            "username" => "kuznetsovanm",
        ],
        [
            "firstName" => "Евгения Петровна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.П.",
            "gender" => "женский",
            "username" => "morozovaep",
        ],
        [
            "firstName" => "Анастасия Сергеевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева А.С.",
            "gender" => "женский",
            "username" => "vasilevaas",
        ],
        [
            "firstName" => "Татьяна Викторовна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Т.В.",
            "gender" => "женский",
            "username" => "kovalevatv",
        ],
        [
            "firstName" => "Нина Александровна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.А.",
            "gender" => "женский",
            "username" => "novikovana",
        ],
        [
            "firstName" => "Елена Владимировна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.В.",
            "gender" => "женский",
            "username" => "sokolovaev",
        ],
        [
            "firstName" => "Анна Анатольевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.А.",
            "gender" => "женский",
            "username" => "kozlovaaa",
        ],
        [
            "firstName" => "Ирина Николаевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.Н.",
            "gender" => "женский",
            "username" => "fedorovain",
        ],
        [
            "firstName" => "Лариса Викторовна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Л.В.",
            "gender" => "женский",
            "username" => "ivanovalv",
        ],
        [
            "firstName" => "Елена Васильевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Е.В.",
            "gender" => "женский",
            "username" => "smirnovaev",
        ],
        [
            "firstName" => "Татьяна Анатольевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Т.А.",
            "gender" => "женский",
            "username" => "petrovata",
        ],
        [
            "firstName" => "Екатерина Петровна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.П.",
            "gender" => "женский",
            "username" => "kuznetsovaep2",
        ],
        [
            "firstName" => "Александра Владимировна",
            "lastName" => "Морозова",
            "shortName" => "Морозова А.В.",
            "gender" => "женский",
            "username" => "morozovaav",
        ],
        [
            "firstName" => "Ольга Викторовна",
            "lastName" => "Васильева",
            "shortName" => "Васильева О.В.",
            "gender" => "женский",
            "username" => "vasilevaov",
        ],
        [
            "firstName" => "Наталья Сергеевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.С.",
            "gender" => "женский",
            "username" => "kovalevans",
        ],
        [
            "firstName" => "Марина Игоревна",
            "lastName" => "Новикова",
            "shortName" => "Новикова М.И.",
            "gender" => "женский",
            "username" => "novikovami",
        ],
        [
            "firstName" => "Екатерина Петровна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.П.",
            "gender" => "женский",
            "username" => "sokolovaep",
        ],
        [
            "firstName" => "Ирина Владимировна",
            "lastName" => "Козлова",
            "shortName" => "Козлова И.В.",
            "gender" => "женский",
            "username" => "kozlovaiv",
        ],
        [
            "firstName" => "Елена Николаевна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.Н.",
            "gender" => "женский",
            "username" => "fedorovaen",
        ],
        [
            "firstName" => "Мария Викторовна",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.В.",
            "gender" => "женский",
            "username" => "ivanovamv2",
        ],
        [
            "firstName" => "Елена Сергеевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Е.С.",
            "gender" => "женский",
            "username" => "smirnovaes",
        ],
        [
            "firstName" => "Ольга Анатольевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.А.",
            "gender" => "женский",
            "username" => "petrovaoa",
        ],
        [
            "firstName" => "Марина Николаевна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова М.Н.",
            "gender" => "женский",
            "username" => "kuznetsovamn",
        ],
        [
            "firstName" => "Людмила Викторовна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Л.В.",
            "gender" => "женский",
            "username" => "morozovalv",
        ],
        [
            "firstName" => "Марина Андреевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева М.А.",
            "gender" => "женский",
            "username" => "vasilevama2",
        ],
        [
            "firstName" => "Людмила Владимировна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Л.В.",
            "gender" => "женский",
            "username" => "kovalevalv",
        ],
        [
            "firstName" => "Наталья Александровна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.А.",
            "gender" => "женский",
            "username" => "novikovana2",
        ],
        [
            "firstName" => "Марина Анатольевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.А.",
            "gender" => "женский",
            "username" => "sokolovama",
        ],
        [
            "firstName" => "Татьяна Сергеевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Т.С.",
            "gender" => "женский",
            "username" => "kozlovats2",
        ],
        [
            "firstName" => "Ольга Петровна",
            "lastName" => "Федорова",
            "shortName" => "Федорова О.П.",
            "gender" => "женский",
            "username" => "fedorovaop",
        ],
        [
            "firstName" => "Екатерина Николаевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Е.Н.",
            "gender" => "женский",
            "username" => "ivanovaen",
        ],
        [
            "firstName" => "Анна Владимировна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.В.",
            "gender" => "женский",
            "username" => "smirnovaav",
        ],
        [
            "firstName" => "Любовь Васильевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Л.В.",
            "gender" => "женский",
            "username" => "petrovalv",
        ],
        [
            "firstName" => "Татьяна Ивановна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.И.",
            "gender" => "женский",
            "username" => "kuznetsovati",
        ],
        [
            "firstName" => "Ирина Владимировна",
            "lastName" => "Морозова",
            "shortName" => "Морозова И.В.",
            "gender" => "женский",
            "username" => "morozovaiv",
        ],
        [
            "firstName" => "Наталья Сергеевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.С.",
            "gender" => "женский",
            "username" => "vasilevans2",
        ],
        [
            "firstName" => "Тамара Петровна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Т.П.",
            "gender" => "женский",
            "username" => "kovalevatp",
        ],
        [
            "firstName" => "Ольга Ивановна",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.И.",
            "gender" => "женский",
            "username" => "novikovaoi",
        ],
        [
            "firstName" => "Татьяна Анатольевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Т.А.",
            "gender" => "женский",
            "username" => "sokolovata",
        ],
        [
            "firstName" => "Екатерина Андреевна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.А.",
            "gender" => "женский",
            "username" => "kozlovaea2",
        ],
        [
            "firstName" => "Елена Викторовна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.В.",
            "gender" => "женский",
            "username" => "fedorovaev",
        ],
        [
            "firstName" => "Александра Александровна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.А.",
            "gender" => "женский",
            "username" => "ivanovaaa",
        ],
        [
            "firstName" => "Ольга Владимировна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова О.В.",
            "gender" => "женский",
            "username" => "smirnovaov",
        ],
        [
            "firstName" => "Наталья Васильевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Н.В.",
            "gender" => "женский",
            "username" => "petrovanv",
        ],
        [
            "firstName" => "Татьяна Игоревна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.И.",
            "gender" => "женский",
            "username" => "kuznetsovati2",
        ],
        [
            "firstName" => "Евгения Сергеевна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.С.",
            "gender" => "женский",
            "username" => "morozovaes",
        ],
        [
            "firstName" => "Елена Владимировна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Е.В.",
            "gender" => "женский",
            "username" => "vasilevaev",
        ],
        [
            "firstName" => "Ирина Андреевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева И.А.",
            "gender" => "женский",
            "username" => "kovalevaia",
        ],
        [
            "firstName" => "Нина Валерьевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.В.",
            "gender" => "женский",
            "username" => "novikovanv",
        ],
        [
            "firstName" => "Татьяна Валерьевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Т.В.",
            "gender" => "женский",
            "username" => "sokolovatv",
        ],
        [
            "firstName" => "Екатерина Викторовна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.В.",
            "gender" => "женский",
            "username" => "kozlovaev",
        ],
        [
            "firstName" => "Наталья Александровна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Н.А.",
            "gender" => "женский",
            "username" => "fedorovana",
        ],
        [
            "firstName" => "Мария Александровна",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.А.",
            "gender" => "женский",
            "username" => "ivanovama",
        ],
        [
            "firstName" => "Ольга Николаевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова О.Н.",
            "gender" => "женский",
            "username" => "smirnovaon",
        ],
        [
            "firstName" => "Нина Владимировна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Н.В.",
            "gender" => "женский",
            "username" => "petrovanv2",
        ],
        [
            "firstName" => "Татьяна Викторовна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.В.",
            "gender" => "женский",
            "username" => "kuznetsovatv",
        ],
        [
            "firstName" => "Любовь Владимировна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Л.В.",
            "gender" => "женский",
            "username" => "morozovalv2",
        ],
        [
            "firstName" => "Екатерина Андреевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева Е.А.",
            "gender" => "женский",
            "username" => "vasilevaea",
        ],
        [
            "firstName" => "Наталья Сергеевна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.С.",
            "gender" => "женский",
            "username" => "kovalevans2",
        ],
        [
            "firstName" => "Елена Николаевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.Н.",
            "gender" => "женский",
            "username" => "novikovaen",
        ],
        [
            "firstName" => "Марина Валерьевна",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.В.",
            "gender" => "женский",
            "username" => "sokolovamv",
        ],
        [
            "firstName" => "Анна Петровна",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.П.",
            "gender" => "женский",
            "username" => "kozlovaap",
        ],
        [
            "firstName" => "Валентина Владимировна",
            "lastName" => "Федорова",
            "shortName" => "Федорова В.В.",
            "gender" => "женский",
            "username" => "fedorovavv",
        ],
        [
            "firstName" => "Галина Сергеевна",
            "lastName" => "Иванова",
            "shortName" => "Иванова Г.С.",
            "gender" => "женский",
            "username" => "ivanovags",
        ],
        [
            "firstName" => "Людмила Николаевна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Л.Н.",
            "gender" => "женский",
            "username" => "smirnovaln",
        ],
        [
            "firstName" => "Ирина Николаевна",
            "lastName" => "Петрова",
            "shortName" => "Петрова И.Н.",
            "gender" => "женский",
            "username" => "petrovain",
        ],
        [
            "firstName" => "Лариса Викторовна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Л.В.",
            "gender" => "женский",
            "username" => "kuznetsovalv",
        ],
        [
            "firstName" => "Надежда Владимировна",
            "lastName" => "Морозова",
            "shortName" => "Морозова Н.В.",
            "gender" => "женский",
            "username" => "morozovanv",
        ],
        [
            "firstName" => "Ольга Сергеевна",
            "lastName" => "Васильева",
            "shortName" => "Васильева О.С.",
            "gender" => "женский",
            "username" => "vasilevaos",
        ],
        [
            "firstName" => "Елена Александровна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.А.",
            "gender" => "женский",
            "username" => "kovalevaea",
        ],
        [
            "firstName" => "Светлана Николаевна",
            "lastName" => "Новикова",
            "shortName" => "Новикова С.Н.",
            "gender" => "женский",
            "username" => "novikovasn",
        ],
        [
            "firstName" => "Марина Ивановна",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.И.",
            "gender" => "женский",
            "username" => "sokolovami",
        ],
        [
            "firstName" => "Елена Ивановна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.И.",
            "gender" => "женский",
            "username" => "kozlovaei",
        ],
        [
            "firstName" => "Анна Ивановна",
            "lastName" => "Попова",
            "shortName" => "Попова А.И.",
            "gender" => "женский",
            "username" => "popovaai",
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        foreach (self::TEACHERS as $teacher) {
            $randomNumber = random_int(1, 12);

            User::factory()
                ->teacher()
                ->create([
                    'username' => $teacher['username'] . "_teacher",
                    'email' => $teacher['username'] . "@teacher.rikedu.ru",
                    'password' => bcrypt('password'),
                    'first_name' => $teacher['firstName'],
                    'last_name' => $teacher['lastName'],
                    'bio' => $faker->sentence(),
                    'image' => 'https://api.ledinhcuong.com/storage/images/default/avatar/' . $randomNumber . '.png',
                    'gender' => $this->convert_gender($teacher['gender']),
                    'date_of_birth' => $faker->date(),
                    'phone' => $faker->phoneNumber,
                    'address' => $faker->address,
                    'department' => $faker->word,
                    'active' => $faker->boolean(),
                    'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                    'email_verified_at' => now(),
                    'remember_token' => Str::random(10),
                ]);
        }

        foreach (self::STUDENTS as $student) {
            $randomNumber = random_int(1, 12);

            User::factory()
                ->student()
                ->create([
                    'username' => $student['username'] . "_student",
                    'email' => $student['username'] . "@student.rikedu.ru",
                    'password' => bcrypt('password'),
                    'first_name' => $student['firstName'],
                    'last_name' => $student['lastName'],
                    'bio' => $faker->sentence(),
                    'image' => 'https://api.ledinhcuong.com/storage/images/default/avatar/' . $randomNumber . '.png',
                    'gender' => $this->convert_gender($student['gender']),
                    'date_of_birth' => $faker->date(),
                    'phone' => $faker->phoneNumber,
                    'address' => $faker->address,
                    'department' => $faker->word,
                    'active' => $faker->boolean(),
                    'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                    'email_verified_at' => now(),
                    'remember_token' => Str::random(10),
                ]);
        }

        foreach (self::PARENTS as $parent) {
            $randomNumber = random_int(1, 12);

            User::factory()
                ->parent()
                ->create([
                    'username' => $parent['username'] . "_parent",
                    'email' => $parent['username'] . "@parent.rikedu.ru",
                    'password' => bcrypt('password'),
                    'first_name' => $parent['firstName'],
                    'last_name' => $parent['lastName'],
                    'bio' => $faker->sentence(),
                    'image' => 'https://api.ledinhcuong.com/storage/images/default/avatar/' . $randomNumber . '.png',
                    'gender' => $this->convert_gender($parent['gender']),
                    'date_of_birth' => $faker->date(),
                    'phone' => $faker->phoneNumber,
                    'address' => $faker->address,
                    'department' => $faker->word,
                    'active' => $faker->boolean(),
                    'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                    'email_verified_at' => now(),
                    'remember_token' => Str::random(10),
                ]);
        }

        User::factory()
            ->superAdmin()
            ->create([
                'username' => 'superadmin',
                'email' => 'superadmin@admin.rikedu.ru',
                'password' => bcrypt('password'),
                'first_name' => $faker->firstName,
                'last_name' => $faker->lastName,
                'bio' => $faker->sentence(),
                'image' => 'https://api.ledinhcuong.com/storage/images/default/avatar/1.png',
                'gender' => $faker->randomElement(['Male', 'Female', 'Other']),
                'date_of_birth' => $faker->date(),
                'phone' => $faker->phoneNumber,
                'address' => $faker->address,
                'department' => $faker->word,
                'active' => $faker->boolean(),
                'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ]);

        $role_parent = Role::findByName('parent');
        $role_student = Role::findByName('student');
        $list_parents = $role_parent->users()->get();
        $list_students = $role_student->users()->get();

        foreach ($list_parents as $index => $parent) {
            $parent->students()->attach($list_students[$index], ['role' => 'student']);
            $list_students[$index]->parents()->attach($parent, ['role' => 'parent']);
        }
    }

    public function convert_gender($gender)
    {
        if ($gender == 'женский') {
            return 'Female';
        }

        if ($gender == 'мужской') {
            return 'Male';
        }

        return 'Other';
    }
}
