<?php

namespace Database\Seeders\Test;

use App\Models\Role;
use App\Models\User;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    const TEACHERS = [
        [
            "firstName" => "Владимирович Евгений",
            "lastName" => "Лебедев",
            "shortName" => "Лебедев Е.В.",
            "gender" => "мужской",
            "username" => "lebedevev",
        ],
        [
            "firstName" => "Андреевна Мария",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева М.А.",
            "gender" => "женский",
            "username" => "kovalevama",
        ],
        [
            "firstName" => "Андреевна Мария",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева М.А.",
            "gender" => "женский",
            "username" => "kovalevama2",
        ],
        [
            "firstName" => "Андреевна Мария",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева М.А.",
            "gender" => "женский",
            "username" => "kovalevama3",
        ],
        [
            "firstName" => "Игоревич Андрей",
            "lastName" => "Попов",
            "shortName" => "Попов А.И.",
            "gender" => "мужской",
            "username" => "popovai",
        ],
        [
            "firstName" => "Сергеевна Оксана",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.С.",
            "gender" => "женский",
            "username" => "petrovaos",
        ],
        [
            "firstName" => "Васильевич Иван",
            "lastName" => "Федоров",
            "shortName" => "Федоров И.В.",
            "gender" => "мужской",
            "username" => "fedoroviv",
        ],
        [
            "firstName" => "Владимировна Анастасия",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.В.",
            "gender" => "женский",
            "username" => "smirnovaav",
        ],
        [
            "firstName" => "Анатольевич Александр",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.А.",
            "gender" => "мужской",
            "username" => "kuznetsovaa",
        ],
        [
            "firstName" => "Викторовна Светлана",
            "lastName" => "Новикова",
            "shortName" => "Новикова С.В.",
            "gender" => "женский",
            "username" => "novikovasv",
        ],
        [
            "firstName" => "Александрович Игорь",
            "lastName" => "Иванов",
            "shortName" => "Иванов И.А.",
            "gender" => "мужской",
            "username" => "ivanovia",
        ],
        [
            "firstName" => "Ивановна Наталья",
            "lastName" => "Козлова",
            "shortName" => "Козлова Н.И.",
            "gender" => "женский",
            "username" => "kozlovani",
        ],
        [
            "firstName" => "Васильевич Дмитрий",
            "lastName" => "Попов",
            "shortName" => "Попов Д.В.",
            "gender" => "мужской",
            "username" => "popovdv",
        ],
        [
            "firstName" => "Ивановна Анастасия",
            "lastName" => "Соколова",
            "shortName" => "Соколова А.И.",
            "gender" => "женский",
            "username" => "sokolovaai",
        ],
        [
            "firstName" => "Владимирович Виктор",
            "lastName" => "Новиков",
            "shortName" => "Новиков В.В.",
            "gender" => "мужской",
            "username" => "novikovvv",
        ],
        [
            "firstName" => "Сергеевна Анна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.С.",
            "gender" => "женский",
            "username" => "ivanovaas",
        ],
        [
            "firstName" => "Васильевич Алексей",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.В.",
            "gender" => "мужской",
            "username" => "fedorovav",
        ],
        [
            "firstName" => "Васильевна Елена",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.В.",
            "gender" => "женский",
            "username" => "petrovaev",
        ],
        [
            "firstName" => "Андреевич Владимир",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов В.А.",
            "gender" => "мужской",
            "username" => "kuznetsovva",
        ],
        [
            "firstName" => "Владимировна Нина",
            "lastName" => "Попова",
            "shortName" => "Попова Н.В.",
            "gender" => "женский",
            "username" => "popovanv",
        ],
        [
            "firstName" => "Петрович Иван",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.П.",
            "gender" => "мужской",
            "username" => "smirnovip",
        ],
        [
            "firstName" => "Александровна Анна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.А.",
            "gender" => "женский",
            "username" => "kovalevaaa",
        ],
        [
            "firstName" => "Сергеевна Ольга",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова О.С.",
            "gender" => "женский",
            "username" => "kuznetsovaos",
        ],
        [
            "firstName" => "Иванович Алексей",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.И.",
            "gender" => "мужской",
            "username" => "ivanovai",
        ],
        [
            "firstName" => "Владимировна Екатерина",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.В.",
            "gender" => "женский",
            "username" => "novikovaev",
        ],
        [
            "firstName" => "Александрович Александр",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.А.",
            "gender" => "мужской",
            "username" => "kozlovaa",
        ],
        [
            "firstName" => "Андреевна Ирина",
            "lastName" => "Попова",
            "shortName" => "Попова И.А.",
            "gender" => "женский",
            "username" => "popovaia",
        ],
        [
            "firstName" => "Иванович Владислав",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.И.",
            "gender" => "мужской",
            "username" => "sokolovvi",
        ],
        [
            "firstName" => "Сергеевна Татьяна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Т.С.",
            "gender" => "женский",
            "username" => "fedorovats",
        ],
        [
            "firstName" => "Александрович Артем",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.А.",
            "gender" => "мужской",
            "username" => "ivanovaa",
        ],
        [
            "firstName" => "Викторовна Юлия",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Ю.В.",
            "gender" => "женский",
            "username" => "kovalevaiuv",
        ],
        [
            "firstName" => "Иванович Сергей",
            "lastName" => "Петров",
            "shortName" => "Петров С.И.",
            "gender" => "мужской",
            "username" => "petrovsi",
        ],
        [
            "firstName" => "Андреевна Нина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Н.А.",
            "gender" => "женский",
            "username" => "kuznetsovana",
        ],
        [
            "firstName" => "Александрович Андрей",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов А.А.",
            "gender" => "мужской",
            "username" => "smirnovaa",
        ],
        [
            "firstName" => "Васильевна Марина",
            "lastName" => "Новикова",
            "shortName" => "Новикова М.В.",
            "gender" => "женский",
            "username" => "novikovamv",
        ],
        [
            "firstName" => "Владимирович Игорь",
            "lastName" => "Козлов",
            "shortName" => "Козлов И.В.",
            "gender" => "мужской",
            "username" => "kozloviv",
        ],
        [
            "firstName" => "Игоревна Елена",
            "lastName" => "Попова",
            "shortName" => "Попова Е.И.",
            "gender" => "женский",
            "username" => "popovaei",
        ],
        [
            "firstName" => "Андреевич Алексей",
            "lastName" => "Соколов",
            "shortName" => "Соколов А.А.",
            "gender" => "мужской",
            "username" => "sokolovaa",
        ],
        [
            "firstName" => "Ивановна Мария",
            "lastName" => "Федорова",
            "shortName" => "Федорова М.И.",
            "gender" => "женский",
            "username" => "fedorovami",
        ],
        [
            "firstName" => "Васильевич Владимир",
            "lastName" => "Иванов",
            "shortName" => "Иванов В.В.",
            "gender" => "мужской",
            "username" => "ivanovvv",
        ],
        [
            "firstName" => "Викторовна Ольга",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева О.В.",
            "gender" => "женский",
            "username" => "kovalevaov",
        ],
        [
            "firstName" => "Владимирович Денис",
            "lastName" => "Петров",
            "shortName" => "Петров Д.В.",
            "gender" => "мужской",
            "username" => "petrovdv",
        ],
        [
            "firstName" => "Андреевич Иван",
            "lastName" => "Иванов",
            "shortName" => "Иванов И.А.",
            "gender" => "мужской",
            "username" => "ivanovia2",
        ],
        [
            "firstName" => "Владимировна Анна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.В.",
            "gender" => "женский",
            "username" => "novikovaav",
        ],
        [
            "firstName" => "Васильевич Владислав",
            "lastName" => "Козлов",
            "shortName" => "Козлов В.В.",
            "gender" => "мужской",
            "username" => "kozlovvv",
        ],
        [
            "firstName" => "Александровна Алина",
            "lastName" => "Попова",
            "shortName" => "Попова А.А.",
            "gender" => "женский",
            "username" => "popovaaa",
        ],
        [
            "firstName" => "Викторович Алексей",
            "lastName" => "Соколов",
            "shortName" => "Соколов А.В.",
            "gender" => "мужской",
            "username" => "sokolovav",
        ],
        [
            "firstName" => "Васильевна Ирина",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.В.",
            "gender" => "женский",
            "username" => "fedorovaiv",
        ],
        [
            "firstName" => "Игоревич Михаил",
            "lastName" => "Иванов",
            "shortName" => "Иванов М.И.",
            "gender" => "мужской",
            "username" => "ivanovmi",
        ],
        [
            "firstName" => "Александровна Ангелина",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.А.",
            "gender" => "женский",
            "username" => "kovalevaaa2",
        ],
        [
            "firstName" => "Сергеевич Петр",
            "lastName" => "Петров",
            "shortName" => "Петров П.С.",
            "gender" => "мужской",
            "username" => "petrovps",
        ],
        [
            "firstName" => "Владимировна Валерия",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова В.В.",
            "gender" => "женский",
            "username" => "kuznetsovavv",
        ],
        [
            "firstName" => "Андреевич Артем",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов А.А.",
            "gender" => "мужской",
            "username" => "smirnovaa2",
        ],
        [
            "firstName" => "Васильевна Надежда",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.В.",
            "gender" => "женский",
            "username" => "novikovanv",
        ],
        [
            "firstName" => "Игоревич Андрей",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.И.",
            "gender" => "мужской",
            "username" => "kozlovai",
        ],
        [
            "firstName" => "Васильевна Екатерина",
            "lastName" => "Попова",
            "shortName" => "Попова Е.В.",
            "gender" => "женский",
            "username" => "popovaev",
        ],
        [
            "firstName" => "Александрович Даниил",
            "lastName" => "Соколов",
            "shortName" => "Соколов Д.А.",
            "gender" => "мужской",
            "username" => "sokolovda",
        ],
        [
            "firstName" => "Александровна Марина",
            "lastName" => "Федорова",
            "shortName" => "Федорова М.А.",
            "gender" => "женский",
            "username" => "fedorovama",
        ],
        [
            "firstName" => "Васильевич Сергей",
            "lastName" => "Иванов",
            "shortName" => "Иванов С.В.",
            "gender" => "мужской",
            "username" => "ivanovsv",
        ],
        [
            "firstName" => "Игоревна Евгения",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.И.",
            "gender" => "женский",
            "username" => "kovalevaei",
        ],
        [
            "firstName" => "Сергеевич Дмитрий",
            "lastName" => "Петров",
            "shortName" => "Петров Д.С.",
            "gender" => "мужской",
            "username" => "petrovds",
        ],
        [
            "firstName" => "Александровна Екатерина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.А.",
            "gender" => "женский",
            "username" => "kuznetsovaea",
        ],
        [
            "firstName" => "Владимировна Марина",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.В.",
            "gender" => "женский",
            "username" => "smirnovamv",
        ],
        [
            "firstName" => "Игоревич Артём",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.И.",
            "gender" => "мужской",
            "username" => "kuznetsovai",
        ],
        [
            "firstName" => "Сергеевна Елизавета",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.С.",
            "gender" => "женский",
            "username" => "sokolovaes",
        ],
        [
            "firstName" => "Фёдорович Иван",
            "lastName" => "Иванов",
            "shortName" => "Иванов И.Ф.",
            "gender" => "мужской",
            "username" => "ivanovif",
        ],
        [
            "firstName" => "Александровна Анастасия",
            "lastName" => "Крылова",
            "shortName" => "Крылова А.А.",
            "gender" => "женский",
            "username" => "krylovaaa",
        ],
        [
            "firstName" => "Андреевич Сергей",
            "lastName" => "Попов",
            "shortName" => "Попов С.А.",
            "gender" => "мужской",
            "username" => "popovsa",
        ],
        [
            "firstName" => "Дмитриевна Дарья",
            "lastName" => "Новикова",
            "shortName" => "Новикова Д.Д.",
            "gender" => "женский",
            "username" => "novikovadd",
        ],
        [
            "firstName" => "Владимирович Максим",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.В.",
            "gender" => "мужской",
            "username" => "morozovmv",
        ],
        [
            "firstName" => "Ивановна Алиса",
            "lastName" => "Кузьмина",
            "shortName" => "Кузьмина А.И.",
            "gender" => "женский",
            "username" => "kuzminaai",
        ],
        [
            "firstName" => "Сергеевич Илья",
            "lastName" => "Куликов",
            "shortName" => "Куликов И.С.",
            "gender" => "мужской",
            "username" => "kulikovis",
        ],
        [
            "firstName" => "Андреевна Анна",
            "lastName" => "Николаева",
            "shortName" => "Николаева А.А.",
            "gender" => "женский",
            "username" => "nikolaevaaa",
        ],
        [
            "firstName" => "Павлович Андрей",
            "lastName" => "Жуков",
            "shortName" => "Жуков А.П.",
            "gender" => "мужской",
            "username" => "zhukovap",
        ],
        [
            "firstName" => "Андреевна Екатерина",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Е.А.",
            "gender" => "женский",
            "username" => "smirnovaea",
        ],
        [
            "firstName" => "Фёдорович Михаил",
            "lastName" => "Волков",
            "shortName" => "Волков М.Ф.",
            "gender" => "мужской",
            "username" => "volkovmf",
        ],
        [
            "firstName" => "Игоревна Алина",
            "lastName" => "Дмитриева",
            "shortName" => "Дмитриева А.И.",
            "gender" => "женский",
            "username" => "dmitrievaai",
        ],
        [
            "firstName" => "Владимирович Денис",
            "lastName" => "Ковалёв",
            "shortName" => "Ковалёв Д.В.",
            "gender" => "мужской",
            "username" => "kovaliovdv",
        ],
        [
            "firstName" => "Сергеевна Александра",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.С.",
            "gender" => "женский",
            "username" => "novikovaas",
        ],
        [
            "firstName" => "Александрович Владимир",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.А.",
            "gender" => "мужской",
            "username" => "sokolovva",
        ],
        [
            "firstName" => "Петровна Кристина",
            "lastName" => "Крылова",
            "shortName" => "Крылова К.П.",
            "gender" => "женский",
            "username" => "krylovakp",
        ],
        [
            "firstName" => "Николаевна Екатерина",
            "lastName" => "Андреева",
            "shortName" => "Андреева Е.Н.",
            "gender" => "женский",
            "username" => "andreevaen",
        ],
        [
            "firstName" => "Сергеевна Виктория",
            "lastName" => "Белова",
            "shortName" => "Белова В.С.",
            "gender" => "женский",
            "username" => "belovavs",
        ],
        [
            "firstName" => "Павловна Владислава",
            "lastName" => "Бурова",
            "shortName" => "Бурова В.П.",
            "gender" => "женский",
            "username" => "burovavp",
        ],
        [
            "firstName" => "Андреевич Леонид",
            "lastName" => "Волков",
            "shortName" => "Волков Л.А.",
            "gender" => "мужской",
            "username" => "volkovla",
        ],
        [
            "firstName" => "Александровна Антонина",
            "lastName" => "Герасимова",
            "shortName" => "Герасимова А.А.",
            "gender" => "женский",
            "username" => "gerasimovaaa",
        ],
        [
            "firstName" => "Иванович Михаил",
            "lastName" => "Гришин",
            "shortName" => "Гришин М.И.",
            "gender" => "мужской",
            "username" => "grishinmi",
        ],
        [
            "firstName" => "Денисовна Ольга",
            "lastName" => "Данилова",
            "shortName" => "Данилова О.Д.",
            "gender" => "женский",
            "username" => "danilovaod",
        ],
        [
            "firstName" => "Александровна Наталья",
            "lastName" => "Ефимова",
            "shortName" => "Ефимова Н.А.",
            "gender" => "женский",
            "username" => "efimovana",
        ],
        [
            "firstName" => "Дмитриевич Сергей",
            "lastName" => "Зайцев",
            "shortName" => "Зайцев С.Д.",
            "gender" => "мужской",
            "username" => "zaitsevsd",
        ],
        [
            "firstName" => "Викторович Евгений",
            "lastName" => "Козлов",
            "shortName" => "Козлов Е.В.",
            "gender" => "мужской",
            "username" => "kozlovev",
        ],
        [
            "firstName" => "Сергеевна Лилия",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Л.С.",
            "gender" => "женский",
            "username" => "kuznetsovals",
        ],
        [
            "firstName" => "Андреевич Никита",
            "lastName" => "Лебедев",
            "shortName" => "Лебедев Н.А.",
            "gender" => "мужской",
            "username" => "lebedevna",
        ],
        [
            "firstName" => "Петрович Василий",
            "lastName" => "Макаров",
            "shortName" => "Макаров В.П.",
            "gender" => "мужской",
            "username" => "makarovvp",
        ],
        [
            "firstName" => "Дмитриевна Алиса",
            "lastName" => "Маркова",
            "shortName" => "Маркова А.Д.",
            "gender" => "женский",
            "username" => "markovaad",
        ],
        [
            "firstName" => "Александрович Иван",
            "lastName" => "Николаев",
            "shortName" => "Николаев И.А.",
            "gender" => "мужской",
            "username" => "nikolaevia",
        ],
        [
            "firstName" => "Валерьевна Татьяна",
            "lastName" => "Орлова",
            "shortName" => "Орлова Т.В.",
            "gender" => "женский",
            "username" => "orlovatv",
        ],
        [
            "firstName" => "Игоревич Антон",
            "lastName" => "Павлов",
            "shortName" => "Павлов А.И.",
            "gender" => "мужской",
            "username" => "pavlovai",
        ],
        [
            "firstName" => "Валерьевна Александра",
            "lastName" => "Петрова",
            "shortName" => "Петрова А.В.",
            "gender" => "женский",
            "username" => "petrovaav",
        ],
        [
            "firstName" => "Викторовна Александра",
            "lastName" => "Андреева",
            "shortName" => "Андреева А.В.",
            "gender" => "женский",
            "username" => "andreevaav",
        ],
        [
            "firstName" => "Михайлович Иван",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.М.",
            "gender" => "мужской",
            "username" => "smirnovim",
        ],
        [
            "firstName" => "Алексеевна Ольга",
            "lastName" => "Попова",
            "shortName" => "Попова О.А.",
            "gender" => "женский",
            "username" => "popovaoa",
        ],
        [
            "firstName" => "Игоревич Андрей",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.И.",
            "gender" => "мужской",
            "username" => "kuznetsovai2",
        ],
        [
            "firstName" => "Анатольевна Екатерина",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.А.",
            "gender" => "женский",
            "username" => "fedorovaea",
        ],
        [
            "firstName" => "Сергеевич Дмитрий",
            "lastName" => "Морозов",
            "shortName" => "Морозов Д.С.",
            "gender" => "мужской",
            "username" => "morozovds",
        ],
        [
            "firstName" => "Владимировна Анна",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.В.",
            "gender" => "женский",
            "username" => "novikovaav2",
        ],
        [
            "firstName" => "Александрович Сергей",
            "lastName" => "Волков",
            "shortName" => "Волков С.А.",
            "gender" => "мужской",
            "username" => "volkovsa",
        ],
        [
            "firstName" => "Васильевна Татьяна",
            "lastName" => "Андреева",
            "shortName" => "Андреева Т.В.",
            "gender" => "женский",
            "username" => "andreevatv",
        ],
        [
            "firstName" => "Иванович Владимир",
            "lastName" => "Петров",
            "shortName" => "Петров В.И.",
            "gender" => "мужской",
            "username" => "petrovvi",
        ],
        [
            "firstName" => "Игоревна Елена",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.И.",
            "gender" => "женский",
            "username" => "sokolovaei",
        ],
        [
            "firstName" => "Павлович Николай",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев Н.П.",
            "gender" => "мужской",
            "username" => "kovalevnp",
        ],
        [
            "firstName" => "Владимировна Марина",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева М.В.",
            "gender" => "женский",
            "username" => "lebedevamv",
        ],
        [
            "firstName" => "Андреевич Алексей",
            "lastName" => "Семенов",
            "shortName" => "Семенов А.А.",
            "gender" => "мужской",
            "username" => "semenovaa",
        ],
        [
            "firstName" => "Дмитриевна Ирина",
            "lastName" => "Егорова",
            "shortName" => "Егорова И.Д.",
            "gender" => "женский",
            "username" => "egorovaid",
        ],
        [
            "firstName" => "Сергеевна Виктория",
            "lastName" => "Павлова",
            "shortName" => "Павлова В.С.",
            "gender" => "женский",
            "username" => "pavlovavs",
        ],
        [
            "firstName" => "Александрович Роман",
            "lastName" => "Васильев",
            "shortName" => "Васильев Р.А.",
            "gender" => "мужской",
            "username" => "vasilevra",
        ],
        [
            "firstName" => "Сергеевич Никита",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Н.С.",
            "gender" => "мужской",
            "username" => "smirnovns",
        ],
        [
            "firstName" => "Павловна Ольга",
            "lastName" => "Иванова",
            "shortName" => "Иванова О.П.",
            "gender" => "женский",
            "username" => "ivanovaop",
        ],
        [
            "firstName" => "Дмитриевич Александр",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.Д.",
            "gender" => "мужской",
            "username" => "kuznetsovad",
        ],
        [
            "firstName" => "Андреевна Ирина",
            "lastName" => "Соколова",
            "shortName" => "Соколова И.А.",
            "gender" => "женский",
            "username" => "sokolovaia",
        ],
        [
            "firstName" => "Владимирович Дмитрий",
            "lastName" => "Попов",
            "shortName" => "Попов Д.В.",
            "gender" => "мужской",
            "username" => "popovdv2",
        ],
        [
            "firstName" => "Михайловна Елена",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева Е.М.",
            "gender" => "женский",
            "username" => "lebedevaem",
        ],
        [
            "firstName" => "Александрович Андрей",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.А.",
            "gender" => "мужской",
            "username" => "kozlovaa2",
        ],
        [
            "firstName" => "Владимировна Ольга",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.В.",
            "gender" => "женский",
            "username" => "novikovaov",
        ],
        [
            "firstName" => "Алексеевич Максим",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.А.",
            "gender" => "мужской",
            "username" => "morozovma",
        ],
        [
            "firstName" => "Ивановна Екатерина",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.И.",
            "gender" => "женский",
            "username" => "petrovaei",
        ],
        [
            "firstName" => "Анатольевич Алексей",
            "lastName" => "Волков",
            "shortName" => "Волков А.А.",
            "gender" => "мужской",
            "username" => "volkovaa",
        ],
        [
            "firstName" => "Андреевна Юлия",
            "lastName" => "Соловьева",
            "shortName" => "Соловьева Ю.А.",
            "gender" => "женский",
            "username" => "solovevaiua",
        ],
        [
            "firstName" => "Викторович Сергей",
            "lastName" => "Васильев",
            "shortName" => "Васильев С.В.",
            "gender" => "мужской",
            "username" => "vasilevsv",
        ],
        [
            "firstName" => "Александровна Надежда",
            "lastName" => "Зайцева",
            "shortName" => "Зайцева Н.А.",
            "gender" => "женский",
            "username" => "zaitsevana",
        ],
        [
            "firstName" => "Игоревич Антон",
            "lastName" => "Павлов",
            "shortName" => "Павлов А.И.",
            "gender" => "мужской",
            "username" => "pavlovai2",
        ],
        [
            "firstName" => "Сергеевна Татьяна",
            "lastName" => "Семенова",
            "shortName" => "Семенова Т.С.",
            "gender" => "женский",
            "username" => "semenovats",
        ],
        [
            "firstName" => "Анатольевич Александр",
            "lastName" => "Григорьев",
            "shortName" => "Григорьев А.А.",
            "gender" => "мужской",
            "username" => "grigorevaa",
        ],
        [
            "firstName" => "Дмитриевна Ирина",
            "lastName" => "Богданова",
            "shortName" => "Богданова И.Д.",
            "gender" => "женский",
            "username" => "bogdanovaid",
        ],
        [
            "firstName" => "Ивановна Екатерина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.И.",
            "gender" => "женский",
            "username" => "kuznetsovaei",
        ],
        [
            "firstName" => "Александрович Андрей",
            "lastName" => "Попов",
            "shortName" => "Попов А.А.",
            "gender" => "мужской",
            "username" => "popovaa",
        ],
        [
            "firstName" => "Сергеевна Ольга",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева О.С.",
            "gender" => "женский",
            "username" => "kovalevaos",
        ],
        [
            "firstName" => "Николаевич Владислав",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов В.Н.",
            "gender" => "мужской",
            "username" => "smirnovvn",
        ],
        [
            "firstName" => "Владимировна Надежда",
            "lastName" => "Иванова",
            "shortName" => "Иванова Н.В.",
            "gender" => "женский",
            "username" => "ivanovanv",
        ],
        [
            "firstName" => "Игоревич Максим",
            "lastName" => "Соколов",
            "shortName" => "Соколов М.И.",
            "gender" => "мужской",
            "username" => "sokolovmi",
        ],
        [
            "firstName" => "Александровна Ирина",
            "lastName" => "Кузьмина",
            "shortName" => "Кузьмина И.А.",
            "gender" => "женский",
            "username" => "kuzminaia",
        ],
        [
            "firstName" => "Сергеевич Артем",
            "lastName" => "Медведев",
            "shortName" => "Медведев А.С.",
            "gender" => "мужской",
            "username" => "medvedevas",
        ],
        [
            "firstName" => "Васильевна Людмила",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева Л.В.",
            "gender" => "женский",
            "username" => "lebedevalv",
        ],
        [
            "firstName" => "Иванович Денис",
            "lastName" => "Николаев",
            "shortName" => "Николаев Д.И.",
            "gender" => "мужской",
            "username" => "nikolaevdi",
        ],
        [
            "firstName" => "Степановна Мария",
            "lastName" => "Волкова",
            "shortName" => "Волкова М.С.",
            "gender" => "женский",
            "username" => "volkovams",
        ],
        [
            "firstName" => "Андреевич Антон",
            "lastName" => "Кузьмин",
            "shortName" => "Кузьмин А.А.",
            "gender" => "мужской",
            "username" => "kuzminaa",
        ],
        [
            "firstName" => "Владимировна Екатерина",
            "lastName" => "Сидорова",
            "shortName" => "Сидорова Е.В.",
            "gender" => "женский",
            "username" => "sidorovaev",
        ],
        [
            "firstName" => "Иванович Роман",
            "lastName" => "Петров",
            "shortName" => "Петров Р.И.",
            "gender" => "мужской",
            "username" => "petrovri",
        ],
        [
            "firstName" => "Дмитриевна Ирина",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.Д.",
            "gender" => "женский",
            "username" => "fedorovaid",
        ],
        [
            "firstName" => "Анатольевич Владислав",
            "lastName" => "Комаров",
            "shortName" => "Комаров В.А.",
            "gender" => "мужской",
            "username" => "komarovva",
        ],
        [
            "firstName" => "Ивановна Оксана",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова О.И.",
            "gender" => "женский",
            "username" => "kuznetsovaoi",
        ],
        [
            "firstName" => "Игоревич Сергей",
            "lastName" => "Белов",
            "shortName" => "Белов С.И.",
            "gender" => "мужской",
            "username" => "belovsi",
        ],
        [
            "firstName" => "Александровна Анастасия",
            "lastName" => "Соловьева",
            "shortName" => "Соловьева А.А.",
            "gender" => "женский",
            "username" => "solovevaaa",
        ],
        [
            "firstName" => "Дмитриевна Ксения",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева К.Д.",
            "gender" => "женский",
            "username" => "kovalevakd",
        ],
        [
            "firstName" => "Игоревич Владимир",
            "lastName" => "Белов",
            "shortName" => "Белов В.И.",
            "gender" => "мужской",
            "username" => "belovvi",
        ],
        [
            "firstName" => "Александровна Нина",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Н.А.",
            "gender" => "женский",
            "username" => "smirnovana",
        ],
        [
            "firstName" => "Сергеевич Артем",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов А.С.",
            "gender" => "мужской",
            "username" => "kuznetsovas",
        ],
        [
            "firstName" => "Александровна Дарья",
            "lastName" => "Попова",
            "shortName" => "Попова Д.А.",
            "gender" => "женский",
            "username" => "popovada",
        ],
        [
            "firstName" => "Владимирович Андрей",
            "lastName" => "Михайлов",
            "shortName" => "Михайлов А.В.",
            "gender" => "мужской",
            "username" => "mikhailovav",
        ],
        [
            "firstName" => "Александровна Марина",
            "lastName" => "Соловьева",
            "shortName" => "Соловьева М.А.",
            "gender" => "женский",
            "username" => "solovevama",
        ],
        [
            "firstName" => "Александрович Игорь",
            "lastName" => "Новиков",
            "shortName" => "Новиков И.А.",
            "gender" => "мужской",
            "username" => "novikovia",
        ],
        [
            "firstName" => "Дмитриевна Елена",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.Д.",
            "gender" => "женский",
            "username" => "petrovaed",
        ],
        [
            "firstName" => "Ильич Константин",
            "lastName" => "Андреев",
            "shortName" => "Андреев К.И.",
            "gender" => "мужской",
            "username" => "andreevki",
        ],
        [
            "firstName" => "Владимировна Ольга",
            "lastName" => "Лебедева",
            "shortName" => "Лебедева О.В.",
            "gender" => "женский",
            "username" => "lebedevaov",
        ],
        [
            "firstName" => "Петровна Валентина",
            "lastName" => "Егорова",
            "shortName" => "Егорова В.П.",
            "gender" => "женский",
            "username" => "egorovavp",
        ],
    ];

    const STUDENTS = [
        [
            "firstName" => "Дмитриевна Елена",
            "lastName" => "Иванова",
            "shortName" => "Иванова Е.Д.",
            "gender" => "женский",
            "username" => "ivanovaed",
        ],
        [
            "firstName" => "Александрович Игорь",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.А.",
            "gender" => "мужской",
            "username" => "smirnovia",
        ],
        [
            "firstName" => "Владимировна Анна",
            "lastName" => "Петрова",
            "shortName" => "Петрова А.В.",
            "gender" => "женский",
            "username" => "petrovaav",
        ],
        [
            "firstName" => "Васильевич Сергей",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов С.В.",
            "gender" => "мужской",
            "username" => "kuznetsovsv",
        ],
        [
            "firstName" => "Ивановна Надежда",
            "lastName" => "Морозова",
            "shortName" => "Морозова Н.И.",
            "gender" => "женский",
            "username" => "morozovani",
        ],
        [
            "firstName" => "Николаевич Петр",
            "lastName" => "Васильев",
            "shortName" => "Васильев П.Н.",
            "gender" => "мужской",
            "username" => "vasilevpn",
        ],
        [
            "firstName" => "Сергеевна Татьяна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Т.С.",
            "gender" => "женский",
            "username" => "kovalevats",
        ],
        [
            "firstName" => "Павлович Илья",
            "lastName" => "Новиков",
            "shortName" => "Новиков И.П.",
            "gender" => "мужской",
            "username" => "novikovip",
        ],
        [
            "firstName" => "Александровна Екатерина",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.А.",
            "gender" => "женский",
            "username" => "sokolovaea",
        ],
        [
            "firstName" => "Викторович Андрей",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.В.",
            "gender" => "мужской",
            "username" => "kozlovav",
        ],
        [
            "firstName" => "Васильевна Ольга",
            "lastName" => "Федорова",
            "shortName" => "Федорова О.В.",
            "gender" => "женский",
            "username" => "fedorovaov",
        ],
        [
            "firstName" => "Сергеевич Дмитрий",
            "lastName" => "Ильин",
            "shortName" => "Ильин Д.С.",
            "gender" => "мужской",
            "username" => "ilinds",
        ],
        [
            "firstName" => "Андреевна Анастасия",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.А.",
            "gender" => "женский",
            "username" => "smirnovaaa",
        ],
        [
            "firstName" => "Владимирович Владимир",
            "lastName" => "Петров",
            "shortName" => "Петров В.В.",
            "gender" => "мужской",
            "username" => "petrovvv",
        ],
        [
            "firstName" => "Сергеевна Алина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова А.С.",
            "gender" => "женский",
            "username" => "kuznetsovaas",
        ],
        [
            "firstName" => "Иванович Георгий",
            "lastName" => "Морозов",
            "shortName" => "Морозов Г.И.",
            "gender" => "мужской",
            "username" => "morozovgi",
        ],
        [
            "firstName" => "Дмитриевна Елена",
            "lastName" => "Васильева",
            "shortName" => "Васильева Е.Д.",
            "gender" => "женский",
            "username" => "vasilevaed",
        ],
        [
            "firstName" => "Владимирович Иван",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев И.В.",
            "gender" => "мужской",
            "username" => "kovaleviv",
        ],
        [
            "firstName" => "Павловна Александра",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.П.",
            "gender" => "женский",
            "username" => "novikovaap",
        ],
        [
            "firstName" => "Александрович Максим",
            "lastName" => "Соколов",
            "shortName" => "Соколов М.А.",
            "gender" => "мужской",
            "username" => "sokolovma",
        ],
        [
            "firstName" => "Сергеевич Артем",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.С.",
            "gender" => "мужской",
            "username" => "fedorovas",
        ],
        [
            "firstName" => "Дмитриевна Анастасия",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.Д.",
            "gender" => "женский",
            "username" => "ivanovaad",
        ],
        [
            "firstName" => "Андреевич Денис",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Д.А.",
            "gender" => "мужской",
            "username" => "smirnovda",
        ],
        [
            "firstName" => "Владимировна Софья",
            "lastName" => "Петрова",
            "shortName" => "Петрова С.В.",
            "gender" => "женский",
            "username" => "petrovasv",
        ],
        [
            "firstName" => "Васильевич Владислав",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов В.В.",
            "gender" => "мужской",
            "username" => "kuznetsovvv",
        ],
        [
            "firstName" => "Ивановна Людмила",
            "lastName" => "Морозова",
            "shortName" => "Морозова Л.И.",
            "gender" => "женский",
            "username" => "morozovali",
        ],
        [
            "firstName" => "Николаевич Николай",
            "lastName" => "Васильев",
            "shortName" => "Васильев Н.Н.",
            "gender" => "мужской",
            "username" => "vasilevnn",
        ],
        [
            "firstName" => "Сергеевна Анастасия",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.С.",
            "gender" => "женский",
            "username" => "kovalevaas",
        ],
        [
            "firstName" => "Викторович Дмитрий",
            "lastName" => "Новиков",
            "shortName" => "Новиков Д.В.",
            "gender" => "мужской",
            "username" => "novikovdv",
        ],
        [
            "firstName" => "Александровна Александра",
            "lastName" => "Соколова",
            "shortName" => "Соколова А.А.",
            "gender" => "женский",
            "username" => "sokolovaaa",
        ],
        [
            "firstName" => "Петрович Илья",
            "lastName" => "Козлов",
            "shortName" => "Козлов И.П.",
            "gender" => "мужской",
            "username" => "kozlovip",
        ],
        [
            "firstName" => "Сергеевна Елизавета",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.С.",
            "gender" => "женский",
            "username" => "fedorovaes",
        ],
        [
            "firstName" => "Дмитриевич Андрей",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.Д.",
            "gender" => "мужской",
            "username" => "ivanovad",
        ],
        [
            "firstName" => "Андреевна Мария",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.А.",
            "gender" => "женский",
            "username" => "smirnovama",
        ],
        [
            "firstName" => "Викторович Сергей",
            "lastName" => "Петров",
            "shortName" => "Петров С.В.",
            "gender" => "мужской",
            "username" => "petrovsv",
        ],
        [
            "firstName" => "Николаевна Екатерина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.Н.",
            "gender" => "женский",
            "username" => "kuznetsovaen",
        ],
        [
            "firstName" => "Иванович Игорь",
            "lastName" => "Морозов",
            "shortName" => "Морозов И.И.",
            "gender" => "мужской",
            "username" => "morozovii",
        ],
        [
            "firstName" => "Дмитриевна Наталья",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.Д.",
            "gender" => "женский",
            "username" => "vasilevand",
        ],
        [
            "firstName" => "Александрович Павел",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев П.А.",
            "gender" => "мужской",
            "username" => "kovalevpa",
        ],
        [
            "firstName" => "Павловна Екатерина",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.П.",
            "gender" => "женский",
            "username" => "novikovaep",
        ],
        [
            "firstName" => "Андреевич Владислав",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.А.",
            "gender" => "мужской",
            "username" => "sokolovva",
        ],
        [
            "firstName" => "Дмитриевна Александра",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.Д.",
            "gender" => "женский",
            "username" => "kozlovaad",
        ],
        [
            "firstName" => "Сергеевич Максим",
            "lastName" => "Федоров",
            "shortName" => "Федоров М.С.",
            "gender" => "мужской",
            "username" => "fedorovms",
        ],
        [
            "firstName" => "Андреевна Анна",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.А.",
            "gender" => "женский",
            "username" => "ivanovaaa",
        ],
        [
            "firstName" => "Петрович Георгий",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Г.П.",
            "gender" => "мужской",
            "username" => "smirnovgp",
        ],
        [
            "firstName" => "Владимировна Марина",
            "lastName" => "Петрова",
            "shortName" => "Петрова М.В.",
            "gender" => "женский",
            "username" => "petrovamv",
        ],
        [
            "firstName" => "Анатольевич Иван",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов И.А.",
            "gender" => "мужской",
            "username" => "kuznetsovia",
        ],
        [
            "firstName" => "Ивановна Надежда",
            "lastName" => "Морозова",
            "shortName" => "Морозова Н.И.",
            "gender" => "женский",
            "username" => "morozovani2",
        ],
        [
            "firstName" => "Николаевич Дмитрий",
            "lastName" => "Васильев",
            "shortName" => "Васильев Д.Н.",
            "gender" => "мужской",
            "username" => "vasilevdn",
        ],
        [
            "firstName" => "Сергеевна Анна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева А.С.",
            "gender" => "женский",
            "username" => "kovalevaas2",
        ],
        [
            "firstName" => "Викторович Андрей",
            "lastName" => "Новиков",
            "shortName" => "Новиков А.В.",
            "gender" => "мужской",
            "username" => "novikovav",
        ],
        [
            "firstName" => "Александровна Екатерина",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.А.",
            "gender" => "женский",
            "username" => "sokolovaea2",
        ],
        [
            "firstName" => "Александрович Степан",
            "lastName" => "Козлов",
            "shortName" => "Козлов С.А.",
            "gender" => "мужской",
            "username" => "kozlovsa",
        ],
        [
            "firstName" => "Владимировна Екатерина",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.В.",
            "gender" => "женский",
            "username" => "fedorovaev",
        ],
        [
            "firstName" => "Андреевич Алексей",
            "lastName" => "Иванов",
            "shortName" => "Иванов А.А.",
            "gender" => "мужской",
            "username" => "ivanovaa",
        ],
        [
            "firstName" => "Викторовна Мария",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.В.",
            "gender" => "женский",
            "username" => "smirnovamv",
        ],
        [
            "firstName" => "Петрович Сергей",
            "lastName" => "Петров",
            "shortName" => "Петров С.П.",
            "gender" => "мужской",
            "username" => "petrovsp",
        ],
        [
            "firstName" => "Николаевна Дарья",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Д.Н.",
            "gender" => "женский",
            "username" => "kuznetsovadn",
        ],
        [
            "firstName" => "Иванович Михаил",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.И.",
            "gender" => "мужской",
            "username" => "morozovmi",
        ],
        [
            "firstName" => "Дмитриевна Анна",
            "lastName" => "Васильева",
            "shortName" => "Васильева А.Д.",
            "gender" => "женский",
            "username" => "vasilevaad",
        ],
        [
            "firstName" => "Павлович Василий",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев В.П.",
            "gender" => "мужской",
            "username" => "kovalevvp",
        ],
        [
            "firstName" => "Александровна Алина",
            "lastName" => "Новикова",
            "shortName" => "Новикова А.А.",
            "gender" => "женский",
            "username" => "novikovaaa",
        ],
        [
            "firstName" => "Андреевич Илья",
            "lastName" => "Соколов",
            "shortName" => "Соколов И.А.",
            "gender" => "мужской",
            "username" => "sokolovia",
        ],
        [
            "firstName" => "Дмитриевна Маргарита",
            "lastName" => "Козлова",
            "shortName" => "Козлова М.Д.",
            "gender" => "женский",
            "username" => "kozlovamd",
        ],
        [
            "firstName" => "Сергеевич Алексей",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.С.",
            "gender" => "мужской",
            "username" => "fedorovas2",
        ],
        [
            "firstName" => "Владимировна Лидия",
            "lastName" => "Иванова",
            "shortName" => "Иванова Л.В.",
            "gender" => "женский",
            "username" => "ivanovalv",
        ],
        [
            "firstName" => "Викторович Даниил",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Д.В.",
            "gender" => "мужской",
            "username" => "smirnovdv",
        ],
        [
            "firstName" => "Андреевна Софья",
            "lastName" => "Петрова",
            "shortName" => "Петрова С.А.",
            "gender" => "женский",
            "username" => "petrovasa",
        ],
        [
            "firstName" => "Игоревна Валерия",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова В.И.",
            "gender" => "женский",
            "username" => "kuznetsovavi",
        ],
        [
            "firstName" => "Николаевич Матвей",
            "lastName" => "Морозов",
            "shortName" => "Морозов М.Н.",
            "gender" => "мужской",
            "username" => "morozovmn",
        ],
        [
            "firstName" => "Владимировна Анастасия",
            "lastName" => "Васильева",
            "shortName" => "Васильева А.В.",
            "gender" => "женский",
            "username" => "vasilevaav",
        ],
        [
            "firstName" => "Анатольевич Артем",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев А.А.",
            "gender" => "мужской",
            "username" => "kovalevaa",
        ],
        [
            "firstName" => "Игоревна Ольга",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.И.",
            "gender" => "женский",
            "username" => "novikovaoi",
        ],
        [
            "firstName" => "Сергеевич Владимир",
            "lastName" => "Соколов",
            "shortName" => "Соколов В.С.",
            "gender" => "мужской",
            "username" => "sokolovvs",
        ],
        [
            "firstName" => "Александровна Юлия",
            "lastName" => "Козлова",
            "shortName" => "Козлова Ю.А.",
            "gender" => "женский",
            "username" => "kozlovaiua",
        ],
        [
            "firstName" => "Васильевич Илья",
            "lastName" => "Федоров",
            "shortName" => "Федоров И.В.",
            "gender" => "мужской",
            "username" => "fedoroviv",
        ],
        [
            "firstName" => "Анатольевна Вероника",
            "lastName" => "Иванова",
            "shortName" => "Иванова В.А.",
            "gender" => "женский",
            "username" => "ivanovava",
        ],
        [
            "firstName" => "Сергеевич Антон",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов А.С.",
            "gender" => "мужской",
            "username" => "smirnovas",
        ],
        [
            "firstName" => "Петровна Ольга",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.П.",
            "gender" => "женский",
            "username" => "petrovaop",
        ],
        [
            "firstName" => "Викторович Дмитрий",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов Д.В.",
            "gender" => "мужской",
            "username" => "kuznetsovdv",
        ],
        [
            "firstName" => "Анатольевна Елена",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.А.",
            "gender" => "женский",
            "username" => "morozovaea",
        ],
        [
            "firstName" => "Александрович Иван",
            "lastName" => "Васильев",
            "shortName" => "Васильев И.А.",
            "gender" => "мужской",
            "username" => "vasilevia",
        ],
        [
            "firstName" => "Викторовна Екатерина",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.В.",
            "gender" => "женский",
            "username" => "kovalevaev",
        ],
        [
            "firstName" => "Сергеевич Павел",
            "lastName" => "Новиков",
            "shortName" => "Новиков П.С.",
            "gender" => "мужской",
            "username" => "novikovps",
        ],
        [
            "firstName" => "Валерьевна Марина",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.В.",
            "gender" => "женский",
            "username" => "sokolovamv",
        ],
        [
            "firstName" => "Александрович Артемий",
            "lastName" => "Козлов",
            "shortName" => "Козлов А.А.",
            "gender" => "мужской",
            "username" => "kozlovaa",
        ],
        [
            "firstName" => "Ильинична Оксана",
            "lastName" => "Федорова",
            "shortName" => "Федорова О.И.",
            "gender" => "женский",
            "username" => "fedorovaoi",
        ],
        [
            "firstName" => "Викторович Михаил",
            "lastName" => "Иванов",
            "shortName" => "Иванов М.В.",
            "gender" => "мужской",
            "username" => "ivanovmv",
        ],
        [
            "firstName" => "Владимировна Анастасия",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.В.",
            "gender" => "женский",
            "username" => "smirnovaav",
        ],
        [
            "firstName" => "Андреевич Вадим",
            "lastName" => "Петров",
            "shortName" => "Петров В.А.",
            "gender" => "мужской",
            "username" => "petrovva",
        ],
        [
            "firstName" => "Владимировна Ирина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова И.В.",
            "gender" => "женский",
            "username" => "kuznetsovaiv",
        ],
        [
            "firstName" => "Николаевич Константин",
            "lastName" => "Морозов",
            "shortName" => "Морозов К.Н.",
            "gender" => "мужской",
            "username" => "morozovkn",
        ],
        [
            "firstName" => "Анатольевна Светлана",
            "lastName" => "Васильева",
            "shortName" => "Васильева С.А.",
            "gender" => "женский",
            "username" => "vasilevasa",
        ],
        [
            "firstName" => "Викторович Андрей",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев А.В.",
            "gender" => "мужской",
            "username" => "kovalevav",
        ],
        [
            "firstName" => "Павловна Евгения",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.П.",
            "gender" => "женский",
            "username" => "novikovaep2",
        ],
        [
            "firstName" => "Андреевич Никита",
            "lastName" => "Соколов",
            "shortName" => "Соколов Н.А.",
            "gender" => "мужской",
            "username" => "sokolovna",
        ],
        [
            "firstName" => "Александровна Алиса",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.А.",
            "gender" => "женский",
            "username" => "kozlovaaa",
        ],
        [
            "firstName" => "Сергеевич Георгий",
            "lastName" => "Федоров",
            "shortName" => "Федоров Г.С.",
            "gender" => "мужской",
            "username" => "fedorovgs",
        ],
        [
            "firstName" => "Александровна Анастасия",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.А.",
            "gender" => "женский",
            "username" => "ivanovaaa2",
        ],
        [
            "firstName" => "Васильевич Денис",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов Д.В.",
            "gender" => "мужской",
            "username" => "smirnovdv2",
        ],
        [
            "firstName" => "Игоревна Елена",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.И.",
            "gender" => "женский",
            "username" => "petrovaei",
        ],
        [
            "firstName" => "Александровна Антонина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова А.А.",
            "gender" => "женский",
            "username" => "kuznetsovaaa",
        ],
        [
            "firstName" => "Викторович Роман",
            "lastName" => "Морозов",
            "shortName" => "Морозов Р.В.",
            "gender" => "мужской",
            "username" => "morozovrv",
        ],
        [
            "firstName" => "Васильевна Ирина",
            "lastName" => "Васильева",
            "shortName" => "Васильева И.В.",
            "gender" => "женский",
            "username" => "vasilevaiv",
        ],
        [
            "firstName" => "Владимирович Александр",
            "lastName" => "Ковалев",
            "shortName" => "Ковалев А.В.",
            "gender" => "мужской",
            "username" => "kovalevav2",
        ],
        [
            "firstName" => "Павловна Ольга",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.П.",
            "gender" => "женский",
            "username" => "novikovaop",
        ],
        [
            "firstName" => "Игоревич Сергей",
            "lastName" => "Соколов",
            "shortName" => "Соколов С.И.",
            "gender" => "мужской",
            "username" => "sokolovsi",
        ],
        [
            "firstName" => "Александровна Маргарита",
            "lastName" => "Козлова",
            "shortName" => "Козлова М.А.",
            "gender" => "женский",
            "username" => "kozlovama",
        ],
        [
            "firstName" => "Владимирович Анатолий",
            "lastName" => "Федоров",
            "shortName" => "Федоров А.В.",
            "gender" => "мужской",
            "username" => "fedorovav",
        ],
        [
            "firstName" => "Ивановна Вера",
            "lastName" => "Иванова",
            "shortName" => "Иванова В.И.",
            "gender" => "женский",
            "username" => "ivanovavi",
        ],
        [
            "firstName" => "Викторович Игорь",
            "lastName" => "Смирнов",
            "shortName" => "Смирнов И.В.",
            "gender" => "мужской",
            "username" => "smirnoviv",
        ],
        [
            "firstName" => "Владимировна Ольга",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.В.",
            "gender" => "женский",
            "username" => "petrovaov",
        ],
        [
            "firstName" => "Андреевич Владимир",
            "lastName" => "Кузнецов",
            "shortName" => "Кузнецов В.А.",
            "gender" => "мужской",
            "username" => "kuznetsovva",
        ],
        [
            "firstName" => "Александровна Марина",
            "lastName" => "Морозова",
            "shortName" => "Морозова М.А.",
            "gender" => "женский",
            "username" => "morozovama",
        ],
        [
            "firstName" => "Васильевич Артем",
            "lastName" => "Васильев",
            "shortName" => "Васильев А.В.",
            "gender" => "мужской",
            "username" => "vasilevav",
        ],
        [
            "firstName" => "Владимировна Евгения",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.В.",
            "gender" => "женский",
            "username" => "kovalevaev2",
        ],
        [
            "firstName" => "Павлович Артемий",
            "lastName" => "Новиков",
            "shortName" => "Новиков А.П.",
            "gender" => "мужской",
            "username" => "novikovap",
        ],
        [
            "firstName" => "Николаевна Елизавета",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.Н.",
            "gender" => "женский",
            "username" => "sokolovaen",
        ],
        [
            "firstName" => "Владимирович Виталий",
            "lastName" => "Козлов",
            "shortName" => "Козлов В.В.",
            "gender" => "мужской",
            "username" => "kozlovvv",
        ],
        [
            "firstName" => "Александровна Ирина",
            "lastName" => "Попова",
            "shortName" => "Попова И.А.",
            "gender" => "женский",
            "username" => "popovaia",
        ],
    ];

    const PARENTS = [
        [
            "firstName" => "Владимировна Ольга",
            "lastName" => "Иванова",
            "shortName" => "Иванова О.В.",
            "gender" => "женский",
            "username" => "ivanovaov",
        ],
        [
            "firstName" => "Сергеевна Наталья",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Н.С.",
            "gender" => "женский",
            "username" => "smirnovans",
        ],
        [
            "firstName" => "Ивановна Елена",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.И.",
            "gender" => "женский",
            "username" => "petrovaei",
        ],
        [
            "firstName" => "Ивановна Евгения",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.И.",
            "gender" => "женский",
            "username" => "kuznetsovaei",
        ],
        [
            "firstName" => "Александровна Анна",
            "lastName" => "Морозова",
            "shortName" => "Морозова А.А.",
            "gender" => "женский",
            "username" => "morozovaaa",
        ],
        [
            "firstName" => "Александровна Мария",
            "lastName" => "Васильева",
            "shortName" => "Васильева М.А.",
            "gender" => "женский",
            "username" => "vasilevama",
        ],
        [
            "firstName" => "Владимировна Оксана",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева О.В.",
            "gender" => "женский",
            "username" => "kovalevaov",
        ],
        [
            "firstName" => "Викторовна Людмила",
            "lastName" => "Новикова",
            "shortName" => "Новикова Л.В.",
            "gender" => "женский",
            "username" => "novikovalv",
        ],
        [
            "firstName" => "Валерьевна Ирина",
            "lastName" => "Соколова",
            "shortName" => "Соколова И.В.",
            "gender" => "женский",
            "username" => "sokolovaiv",
        ],
        [
            "firstName" => "Сергеевна Татьяна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Т.С.",
            "gender" => "женский",
            "username" => "kozlovats",
        ],
        [
            "firstName" => "Александровна Елена",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.А.",
            "gender" => "женский",
            "username" => "fedorovaea",
        ],
        [
            "firstName" => "Петровна Евгения",
            "lastName" => "Ильина",
            "shortName" => "Ильина Е.П.",
            "gender" => "женский",
            "username" => "ilinaep",
        ],
        [
            "firstName" => "Сергеевна Лариса",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Л.С.",
            "gender" => "женский",
            "username" => "smirnovals",
        ],
        [
            "firstName" => "Владимировна Оксана",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.В.",
            "gender" => "женский",
            "username" => "petrovaov",
        ],
        [
            "firstName" => "Александровна Татьяна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.А.",
            "gender" => "женский",
            "username" => "kuznetsovata",
        ],
        [
            "firstName" => "Викторовна Елена",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.В.",
            "gender" => "женский",
            "username" => "morozovaev",
        ],
        [
            "firstName" => "Николаевна Нина",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.Н.",
            "gender" => "женский",
            "username" => "vasilevann",
        ],
        [
            "firstName" => "Андреевна Надежда",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.А.",
            "gender" => "женский",
            "username" => "kovalevana",
        ],
        [
            "firstName" => "Викторовна Ольга",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.В.",
            "gender" => "женский",
            "username" => "novikovaov",
        ],
        [
            "firstName" => "Владимировна Алла",
            "lastName" => "Соколова",
            "shortName" => "Соколова А.В.",
            "gender" => "женский",
            "username" => "sokolovaav",
        ],
        [
            "firstName" => "Анатольевна Ирина",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.А.",
            "gender" => "женский",
            "username" => "fedorovaia",
        ],
        [
            "firstName" => "Викторовна Марина",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.В.",
            "gender" => "женский",
            "username" => "ivanovamv",
        ],
        [
            "firstName" => "Петровна Лидия",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Л.П.",
            "gender" => "женский",
            "username" => "smirnovalp",
        ],
        [
            "firstName" => "Викторовна Евгения",
            "lastName" => "Петрова",
            "shortName" => "Петрова Е.В.",
            "gender" => "женский",
            "username" => "petrovaev",
        ],
        [
            "firstName" => "Ивановна Анна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова А.И.",
            "gender" => "женский",
            "username" => "kuznetsovaai",
        ],
        [
            "firstName" => "Владимировна Евгения",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.В.",
            "gender" => "женский",
            "username" => "morozovaev2",
        ],
        [
            "firstName" => "Степановна Наталья",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.С.",
            "gender" => "женский",
            "username" => "vasilevans",
        ],
        [
            "firstName" => "Николаевна Наталья",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.Н.",
            "gender" => "женский",
            "username" => "kovalevann",
        ],
        [
            "firstName" => "Сергеевна Елена",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.С.",
            "gender" => "женский",
            "username" => "novikovaes",
        ],
        [
            "firstName" => "Николаевна Ирина",
            "lastName" => "Соколова",
            "shortName" => "Соколова И.Н.",
            "gender" => "женский",
            "username" => "sokolovain",
        ],
        [
            "firstName" => "Александровна Мария",
            "lastName" => "Козлова",
            "shortName" => "Козлова М.А.",
            "gender" => "женский",
            "username" => "kozlovama",
        ],
        [
            "firstName" => "Ивановна Людмила",
            "lastName" => "Федорова",
            "shortName" => "Федорова Л.И.",
            "gender" => "женский",
            "username" => "fedorovali",
        ],
        [
            "firstName" => "Ивановна Марина",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.И.",
            "gender" => "женский",
            "username" => "ivanovami",
        ],
        [
            "firstName" => "Андреевна Анна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.А.",
            "gender" => "женский",
            "username" => "smirnovaaa",
        ],
        [
            "firstName" => "Александровна Нина",
            "lastName" => "Петрова",
            "shortName" => "Петрова Н.А.",
            "gender" => "женский",
            "username" => "petrovana",
        ],
        [
            "firstName" => "Петровна Елена",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.П.",
            "gender" => "женский",
            "username" => "kuznetsovaep",
        ],
        [
            "firstName" => "Анатольевна Елена",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.А.",
            "gender" => "женский",
            "username" => "morozovaea",
        ],
        [
            "firstName" => "Павловна Оксана",
            "lastName" => "Васильева",
            "shortName" => "Васильева О.П.",
            "gender" => "женский",
            "username" => "vasilevaop",
        ],
        [
            "firstName" => "Петровна Ирина",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева И.П.",
            "gender" => "женский",
            "username" => "kovalevaip",
        ],
        [
            "firstName" => "Владимировна Татьяна",
            "lastName" => "Новикова",
            "shortName" => "Новикова Т.В.",
            "gender" => "женский",
            "username" => "novikovatv",
        ],
        [
            "firstName" => "Игоревна Наталья",
            "lastName" => "Соколова",
            "shortName" => "Соколова Н.И.",
            "gender" => "женский",
            "username" => "sokolovani",
        ],
        [
            "firstName" => "Андреевна Елена",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.А.",
            "gender" => "женский",
            "username" => "kozlovaea",
        ],
        [
            "firstName" => "Александровна Татьяна",
            "lastName" => "Федорова",
            "shortName" => "Федорова Т.А.",
            "gender" => "женский",
            "username" => "fedorovata",
        ],
        [
            "firstName" => "Владимировна Екатерина",
            "lastName" => "Иванова",
            "shortName" => "Иванова Е.В.",
            "gender" => "женский",
            "username" => "ivanovaev",
        ],
        [
            "firstName" => "Сергеевна Марина",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова М.С.",
            "gender" => "женский",
            "username" => "smirnovams",
        ],
        [
            "firstName" => "Александровна Александра",
            "lastName" => "Петрова",
            "shortName" => "Петрова А.А.",
            "gender" => "женский",
            "username" => "petrovaaa",
        ],
        [
            "firstName" => "Михайловна Наталья",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Н.М.",
            "gender" => "женский",
            "username" => "kuznetsovanm",
        ],
        [
            "firstName" => "Петровна Евгения",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.П.",
            "gender" => "женский",
            "username" => "morozovaep",
        ],
        [
            "firstName" => "Сергеевна Анастасия",
            "lastName" => "Васильева",
            "shortName" => "Васильева А.С.",
            "gender" => "женский",
            "username" => "vasilevaas",
        ],
        [
            "firstName" => "Викторовна Татьяна",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Т.В.",
            "gender" => "женский",
            "username" => "kovalevatv",
        ],
        [
            "firstName" => "Александровна Нина",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.А.",
            "gender" => "женский",
            "username" => "novikovana",
        ],
        [
            "firstName" => "Владимировна Елена",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.В.",
            "gender" => "женский",
            "username" => "sokolovaev",
        ],
        [
            "firstName" => "Анатольевна Анна",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.А.",
            "gender" => "женский",
            "username" => "kozlovaaa",
        ],
        [
            "firstName" => "Николаевна Ирина",
            "lastName" => "Федорова",
            "shortName" => "Федорова И.Н.",
            "gender" => "женский",
            "username" => "fedorovain",
        ],
        [
            "firstName" => "Викторовна Лариса",
            "lastName" => "Иванова",
            "shortName" => "Иванова Л.В.",
            "gender" => "женский",
            "username" => "ivanovalv",
        ],
        [
            "firstName" => "Васильевна Елена",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Е.В.",
            "gender" => "женский",
            "username" => "smirnovaev",
        ],
        [
            "firstName" => "Анатольевна Татьяна",
            "lastName" => "Петрова",
            "shortName" => "Петрова Т.А.",
            "gender" => "женский",
            "username" => "petrovata",
        ],
        [
            "firstName" => "Петровна Екатерина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Е.П.",
            "gender" => "женский",
            "username" => "kuznetsovaep2",
        ],
        [
            "firstName" => "Владимировна Александра",
            "lastName" => "Морозова",
            "shortName" => "Морозова А.В.",
            "gender" => "женский",
            "username" => "morozovaav",
        ],
        [
            "firstName" => "Викторовна Ольга",
            "lastName" => "Васильева",
            "shortName" => "Васильева О.В.",
            "gender" => "женский",
            "username" => "vasilevaov",
        ],
        [
            "firstName" => "Сергеевна Наталья",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.С.",
            "gender" => "женский",
            "username" => "kovalevans",
        ],
        [
            "firstName" => "Игоревна Марина",
            "lastName" => "Новикова",
            "shortName" => "Новикова М.И.",
            "gender" => "женский",
            "username" => "novikovami",
        ],
        [
            "firstName" => "Петровна Екатерина",
            "lastName" => "Соколова",
            "shortName" => "Соколова Е.П.",
            "gender" => "женский",
            "username" => "sokolovaep",
        ],
        [
            "firstName" => "Владимировна Ирина",
            "lastName" => "Козлова",
            "shortName" => "Козлова И.В.",
            "gender" => "женский",
            "username" => "kozlovaiv",
        ],
        [
            "firstName" => "Николаевна Елена",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.Н.",
            "gender" => "женский",
            "username" => "fedorovaen",
        ],
        [
            "firstName" => "Викторовна Мария",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.В.",
            "gender" => "женский",
            "username" => "ivanovamv2",
        ],
        [
            "firstName" => "Сергеевна Елена",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Е.С.",
            "gender" => "женский",
            "username" => "smirnovaes",
        ],
        [
            "firstName" => "Анатольевна Ольга",
            "lastName" => "Петрова",
            "shortName" => "Петрова О.А.",
            "gender" => "женский",
            "username" => "petrovaoa",
        ],
        [
            "firstName" => "Николаевна Марина",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова М.Н.",
            "gender" => "женский",
            "username" => "kuznetsovamn",
        ],
        [
            "firstName" => "Викторовна Людмила",
            "lastName" => "Морозова",
            "shortName" => "Морозова Л.В.",
            "gender" => "женский",
            "username" => "morozovalv",
        ],
        [
            "firstName" => "Андреевна Марина",
            "lastName" => "Васильева",
            "shortName" => "Васильева М.А.",
            "gender" => "женский",
            "username" => "vasilevama2",
        ],
        [
            "firstName" => "Владимировна Людмила",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Л.В.",
            "gender" => "женский",
            "username" => "kovalevalv",
        ],
        [
            "firstName" => "Александровна Наталья",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.А.",
            "gender" => "женский",
            "username" => "novikovana2",
        ],
        [
            "firstName" => "Анатольевна Марина",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.А.",
            "gender" => "женский",
            "username" => "sokolovama",
        ],
        [
            "firstName" => "Сергеевна Татьяна",
            "lastName" => "Козлова",
            "shortName" => "Козлова Т.С.",
            "gender" => "женский",
            "username" => "kozlovats2",
        ],
        [
            "firstName" => "Петровна Ольга",
            "lastName" => "Федорова",
            "shortName" => "Федорова О.П.",
            "gender" => "женский",
            "username" => "fedorovaop",
        ],
        [
            "firstName" => "Николаевна Екатерина",
            "lastName" => "Иванова",
            "shortName" => "Иванова Е.Н.",
            "gender" => "женский",
            "username" => "ivanovaen",
        ],
        [
            "firstName" => "Владимировна Анна",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова А.В.",
            "gender" => "женский",
            "username" => "smirnovaav",
        ],
        [
            "firstName" => "Васильевна Любовь",
            "lastName" => "Петрова",
            "shortName" => "Петрова Л.В.",
            "gender" => "женский",
            "username" => "petrovalv",
        ],
        [
            "firstName" => "Ивановна Татьяна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.И.",
            "gender" => "женский",
            "username" => "kuznetsovati",
        ],
        [
            "firstName" => "Владимировна Ирина",
            "lastName" => "Морозова",
            "shortName" => "Морозова И.В.",
            "gender" => "женский",
            "username" => "morozovaiv",
        ],
        [
            "firstName" => "Сергеевна Наталья",
            "lastName" => "Васильева",
            "shortName" => "Васильева Н.С.",
            "gender" => "женский",
            "username" => "vasilevans2",
        ],
        [
            "firstName" => "Петровна Тамара",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Т.П.",
            "gender" => "женский",
            "username" => "kovalevatp",
        ],
        [
            "firstName" => "Ивановна Ольга",
            "lastName" => "Новикова",
            "shortName" => "Новикова О.И.",
            "gender" => "женский",
            "username" => "novikovaoi",
        ],
        [
            "firstName" => "Анатольевна Татьяна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Т.А.",
            "gender" => "женский",
            "username" => "sokolovata",
        ],
        [
            "firstName" => "Андреевна Екатерина",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.А.",
            "gender" => "женский",
            "username" => "kozlovaea2",
        ],
        [
            "firstName" => "Викторовна Елена",
            "lastName" => "Федорова",
            "shortName" => "Федорова Е.В.",
            "gender" => "женский",
            "username" => "fedorovaev",
        ],
        [
            "firstName" => "Александровна Александра",
            "lastName" => "Иванова",
            "shortName" => "Иванова А.А.",
            "gender" => "женский",
            "username" => "ivanovaaa",
        ],
        [
            "firstName" => "Владимировна Ольга",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова О.В.",
            "gender" => "женский",
            "username" => "smirnovaov",
        ],
        [
            "firstName" => "Васильевна Наталья",
            "lastName" => "Петрова",
            "shortName" => "Петрова Н.В.",
            "gender" => "женский",
            "username" => "petrovanv",
        ],
        [
            "firstName" => "Игоревна Татьяна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.И.",
            "gender" => "женский",
            "username" => "kuznetsovati2",
        ],
        [
            "firstName" => "Сергеевна Евгения",
            "lastName" => "Морозова",
            "shortName" => "Морозова Е.С.",
            "gender" => "женский",
            "username" => "morozovaes",
        ],
        [
            "firstName" => "Владимировна Елена",
            "lastName" => "Васильева",
            "shortName" => "Васильева Е.В.",
            "gender" => "женский",
            "username" => "vasilevaev",
        ],
        [
            "firstName" => "Андреевна Ирина",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева И.А.",
            "gender" => "женский",
            "username" => "kovalevaia",
        ],
        [
            "firstName" => "Валерьевна Нина",
            "lastName" => "Новикова",
            "shortName" => "Новикова Н.В.",
            "gender" => "женский",
            "username" => "novikovanv",
        ],
        [
            "firstName" => "Валерьевна Татьяна",
            "lastName" => "Соколова",
            "shortName" => "Соколова Т.В.",
            "gender" => "женский",
            "username" => "sokolovatv",
        ],
        [
            "firstName" => "Викторовна Екатерина",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.В.",
            "gender" => "женский",
            "username" => "kozlovaev",
        ],
        [
            "firstName" => "Александровна Наталья",
            "lastName" => "Федорова",
            "shortName" => "Федорова Н.А.",
            "gender" => "женский",
            "username" => "fedorovana",
        ],
        [
            "firstName" => "Александровна Мария",
            "lastName" => "Иванова",
            "shortName" => "Иванова М.А.",
            "gender" => "женский",
            "username" => "ivanovama",
        ],
        [
            "firstName" => "Николаевна Ольга",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова О.Н.",
            "gender" => "женский",
            "username" => "smirnovaon",
        ],
        [
            "firstName" => "Владимировна Нина",
            "lastName" => "Петрова",
            "shortName" => "Петрова Н.В.",
            "gender" => "женский",
            "username" => "petrovanv2",
        ],
        [
            "firstName" => "Викторовна Татьяна",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Т.В.",
            "gender" => "женский",
            "username" => "kuznetsovatv",
        ],
        [
            "firstName" => "Владимировна Любовь",
            "lastName" => "Морозова",
            "shortName" => "Морозова Л.В.",
            "gender" => "женский",
            "username" => "morozovalv2",
        ],
        [
            "firstName" => "Андреевна Екатерина",
            "lastName" => "Васильева",
            "shortName" => "Васильева Е.А.",
            "gender" => "женский",
            "username" => "vasilevaea",
        ],
        [
            "firstName" => "Сергеевна Наталья",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Н.С.",
            "gender" => "женский",
            "username" => "kovalevans2",
        ],
        [
            "firstName" => "Николаевна Елена",
            "lastName" => "Новикова",
            "shortName" => "Новикова Е.Н.",
            "gender" => "женский",
            "username" => "novikovaen",
        ],
        [
            "firstName" => "Валерьевна Марина",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.В.",
            "gender" => "женский",
            "username" => "sokolovamv",
        ],
        [
            "firstName" => "Петровна Анна",
            "lastName" => "Козлова",
            "shortName" => "Козлова А.П.",
            "gender" => "женский",
            "username" => "kozlovaap",
        ],
        [
            "firstName" => "Владимировна Валентина",
            "lastName" => "Федорова",
            "shortName" => "Федорова В.В.",
            "gender" => "женский",
            "username" => "fedorovavv",
        ],
        [
            "firstName" => "Сергеевна Галина",
            "lastName" => "Иванова",
            "shortName" => "Иванова Г.С.",
            "gender" => "женский",
            "username" => "ivanovags",
        ],
        [
            "firstName" => "Николаевна Людмила",
            "lastName" => "Смирнова",
            "shortName" => "Смирнова Л.Н.",
            "gender" => "женский",
            "username" => "smirnovaln",
        ],
        [
            "firstName" => "Николаевна Ирина",
            "lastName" => "Петрова",
            "shortName" => "Петрова И.Н.",
            "gender" => "женский",
            "username" => "petrovain",
        ],
        [
            "firstName" => "Викторовна Лариса",
            "lastName" => "Кузнецова",
            "shortName" => "Кузнецова Л.В.",
            "gender" => "женский",
            "username" => "kuznetsovalv",
        ],
        [
            "firstName" => "Владимировна Надежда",
            "lastName" => "Морозова",
            "shortName" => "Морозова Н.В.",
            "gender" => "женский",
            "username" => "morozovanv",
        ],
        [
            "firstName" => "Сергеевна Ольга",
            "lastName" => "Васильева",
            "shortName" => "Васильева О.С.",
            "gender" => "женский",
            "username" => "vasilevaos",
        ],
        [
            "firstName" => "Александровна Елена",
            "lastName" => "Ковалева",
            "shortName" => "Ковалева Е.А.",
            "gender" => "женский",
            "username" => "kovalevaea",
        ],
        [
            "firstName" => "Николаевна Светлана",
            "lastName" => "Новикова",
            "shortName" => "Новикова С.Н.",
            "gender" => "женский",
            "username" => "novikovasn",
        ],
        [
            "firstName" => "Ивановна Марина",
            "lastName" => "Соколова",
            "shortName" => "Соколова М.И.",
            "gender" => "женский",
            "username" => "sokolovami",
        ],
        [
            "firstName" => "Ивановна Елена",
            "lastName" => "Козлова",
            "shortName" => "Козлова Е.И.",
            "gender" => "женский",
            "username" => "kozlovaei",
        ],
        [
            "firstName" => "Ивановна Анна",
            "lastName" => "Попова",
            "shortName" => "Попова А.И.",
            "gender" => "женский",
            "username" => "popovaai",
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        foreach (self::TEACHERS as $teacher) {
            User::factory()
                ->teacher()
                ->create([
                    'username' => $teacher['username'] . "_teacher",
                    'email' => $teacher['username'] . "@teacher.rikedu.ru",
                    'password' => bcrypt('password'),
                    'first_name' => $teacher['firstName'],
                    'last_name' => $teacher['lastName'],
                    'bio' => $faker->sentence(),
                    'image' => 'https://picsum.photos/seed/avatar/600/600.webp',
                    'gender' => $this->convert_gender($teacher['gender']),
                    'date_of_birth' => $faker->date(),
                    'phone' => $faker->phoneNumber,
                    'address' => $faker->address,
                    'department' => $faker->word,
                    'active' => $faker->boolean(),
                    'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                    'email_verified_at' => now(),
                    'remember_token' => Str::random(10),
                ]);
        }

        foreach (self::STUDENTS as $student) {
            User::factory()
                ->student()
                ->create([
                    'username' => $student['username'] . "_student",
                    'email' => $student['username'] . "@student.rikedu.ru",
                    'password' => bcrypt('password'),
                    'first_name' => $student['firstName'],
                    'last_name' => $student['lastName'],
                    'bio' => $faker->sentence(),
                    'image' => 'https://picsum.photos/seed/avatar/600/600.webp',
                    'gender' => $this->convert_gender($student['gender']),
                    'date_of_birth' => $faker->date(),
                    'phone' => $faker->phoneNumber,
                    'address' => $faker->address,
                    'department' => $faker->word,
                    'active' => $faker->boolean(),
                    'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                    'email_verified_at' => now(),
                    'remember_token' => Str::random(10),
                ]);
        }

        foreach (self::PARENTS as $parent) {
            User::factory()
                ->parent()
                ->create([
                    'username' => $parent['username'] . "_parent",
                    'email' => $parent['username'] . "@parent.rikedu.ru",
                    'password' => bcrypt('password'),
                    'first_name' => $parent['firstName'],
                    'last_name' => $parent['lastName'],
                    'bio' => $faker->sentence(),
                    'image' => 'https://picsum.photos/seed/avatar/600/600.webp',
                    'gender' => $this->convert_gender($parent['gender']),
                    'date_of_birth' => $faker->date(),
                    'phone' => $faker->phoneNumber,
                    'address' => $faker->address,
                    'department' => $faker->word,
                    'active' => $faker->boolean(),
                    'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                    'email_verified_at' => now(),
                    'remember_token' => Str::random(10),
                ]);
        }

        User::factory()
            ->superAdmin()
            ->hasPosts(10)
            ->create([
                'username' => 'superadmin',
                'email' => 'superadmin@admin.rikedu.ru',
                'password' => bcrypt('password'),
                'first_name' => $faker->firstName,
                'last_name' => $faker->lastName,
                'bio' => $faker->sentence(),
                'image' => 'https://picsum.photos/seed/avatar/600/600.webp',
                'gender' => $faker->randomElement(['Male', 'Female', 'Other']),
                'date_of_birth' => $faker->date(),
                'phone' => $faker->phoneNumber,
                'address' => $faker->address,
                'department' => $faker->word,
                'active' => $faker->boolean(),
                'last_login' => $faker->dateTimeBetween('-1 day', 'now'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
            ]);

        $role_parent = Role::findByName('parent');
        $role_student = Role::findByName('student');
        $list_parents = $role_parent->users()->get();
        $list_students = $role_student->users()->get();

        foreach ($list_parents as $index => $parent) {
            $parent->students()->attach($list_students[$index], ['role' => 'student']);
            $list_students[$index]->parents()->attach($parent, ['role' => 'parent']);
        }
    }

    public function convert_gender($gender)
    {
        if ($gender == 'женский') {
            return 'Female';
        }

        if ($gender == 'мужской') {
            return 'Male';
        }

        return 'Other';
    }
}
